### ISSUE TITLE
日照量與、速計及蒐集器提問

### ISSUE THREAD

**Issue by coolwang2** [taipower-dreams-tester/dreams-cloud-joint-tester#10]
您好：

請問「日照量」與「風速計」的參數有要一起回報嗎？
以及
6-2，我們試著發出定時的資料給dream,但發現需要等到dream發all class的request, 時，我們回應後，才會通過，但我們測了好幾次，發現dream不一定會發all class request,我們想知道，除了定時的資料外，我們還需要發什麼數據，才能讓dream 發出all class request

謝謝

![image](https://user-images.githubusercontent.com/16569335/105299125-78660880-5bf5-11eb-9cb6-61fbb40e5784.png)

**Comment by taipower-dreams-tester** [comment]
您好，
點位上應該要一起回報，但如文件後方附註所示，僅太陽光電案場需保證日照量數值正確，也僅有風力發電案場須保證風速值正確。

另外依規範 ["台灣電力公司配電級再生能源監控設備(再生能源監控設備/業者雲端資料系統)與 DREAMS傳輸需求技術規範摘要"](https://www.taipower.com.tw/upload/123/2021011514372039094.pdf)所述，all class polling僅有當DREAMS重啟時應當發出。6-2應由Outstation在復線後自行發出class 1的Event定時資料。

**Comment by coolwang2** [comment]
你好，
但我們發現，只有當dream 發出all class request，然後我們回覆後，6-2才會pass, 若沒有，則都不會pass,這是為什麼？
謝謝.

**Comment by taipower-dreams-tester** [comment]
您好，
請問在all class request之前您有確實發送完整的class1 Event資訊嗎?
另外6-2的情況不應該發出all class request，這點我們會查明後再回覆。
謝謝!

**Comment by coolwang2** [comment]
您好，
我們在all class request之前有發送完整的class1 Event資訊。
謝謝

**Comment by coolwang2** [comment]
您好：
是不是發出夠多的 Class1/2 Event 的資料後， dream 會突然來要 all class request 呢？
謝謝

**Comment by taipower-dreams-tester** [comment]
您好，
測試程式的程式碼裡面並沒有實作過這樣的邏輯喔，就過去的實測經驗也沒有遇過這樣的情形。
方便提供比較確切的重製步驟嗎?
謝謝!

**Comment by taipower-dreams-tester** [comment]
No activities since 4 Feb, close the issue
