### ISSUE TITLE
5-2 / 6-2 斷線後復線，是要收到「前一筆最近的整點資料」還是等「未來的整點資料」

### ISSUE THREAD

**Issue by coolwang2** [taipower-dreams-tester/dreams-cloud-joint-tester#11]
5-2 雲端系統斷線後復線：表示中間傳不了資料給 dream, 請問復線後，dream 是要收到「過去最近的整點資料」還是等「未來最近的整點資料」

6-2 蒐集器斷線後復線：表示中間傳不了資料給 dream, 請問復線後，dream 是要收到「過去最近的整點資料」還是等「未來最近的整點資料」

**Comment by coolwang2** [comment]
您好，
不過 6-2 是在 6-1 將「蒐集器斷電」，所以已經沒有在蒐集資料了，請問 6-2 如何拿到「過去最近的整點資料」呢？
以及
6-1 的描述：「手動將現場資料蒐集器斷電。手動將現場資料蒐集器斷電後再按下測試按鈕，DREAMS模擬伺服器應可見可控案場離線。」
為什麼「蒐集器斷電」與「案場離線」會有關係呢？
蒐集器斷電如何讓案場離線呢？
蒐集器復電了，如何拿到「過去最近的整點資料」，「過去最近的整點資料」要存哪呢？

**Comment by taipower-dreams-tester** [comment]
您好，
所謂「過去最近的整點資料」是指復線當下能夠拿到的過去最近整點資料，因此蒐集器斷電的情況下應回傳的是斷電前最後一筆整點資料喔。

**Comment by coolwang2** [comment]
您好，

因為「蒐集器斷電」可能很久(好幾個小時以上)，所以當「蒐集器復線上電」後，案場要去傳送「蒐集器斷電」前有拿到最近的整點資料(而這筆整點資料曾經也有傳送給 dream，因為當時蒐集器還沒斷電)。
如此，dream 會收到兩筆重覆的整點資料，而「蒐集器斷電」期間的整點資料一律放棄不管。
是這樣解讀嗎？

謝謝

**Comment by taipower-dreams-tester** [comment]
您好，
依台電現行規範，是這樣解讀沒錯。

**Comment by sunwareIzumi** [comment]
我想問一下 5-1 斷線後

5-2 重新連上 
DNP3-master 不會重新發起連線

要如何取得連線資料 拋送資料回去給 dnp3-master ??

**Comment by taipower-dreams-tester** [comment]
您好，如果您的outstation有正常斷線，DNP master應該會重新發起連線喔。
方便請問您的斷線方式嗎?

另外如果問題已經解決，再麻煩將issue關閉。
感謝!
