### ISSUE TITLE
[WebAPI] 500 Internal Error

### ISSUE THREAD

**Issue by MKTtoolman** [taipower-dreams-tester/dreams-cloud-joint-tester#12]
根據手冊向WebAPI索取DNP3地址

> https://172.16.1.131/api/plants/plantMeterNo/99-99-9999-99-9?token=site_token_for_cloud_jointer

API報錯 500 Internal Server Error

>'{"error":{"statusCode":500,"message":"Internal Server Error"}}

查詢master log.

> > loopback-getting-started@1.0.0 start-nossl /rest-api-dreams
> > cross-env NODE_ENV=production node .
> 
> Plants settings.validateUpsert was overriden to false
> Unhandled error for request GET /api/plants/plantMeterNo/99-99-9999-99-9?token=site_token_for_cloud_jointer: [object Object]
> Unhandled error for request GET /api/plants/plantMeterNo/99-99-9999-99-9?token=site_token_for_cloud_jointer: [object Object]
> 
> > loopback-getting-started@1.0.0 start-nossl /rest-api-dreams
> > cross-env NODE_ENV=production node .
> 
> Plants settings.validateUpsert was overriden to false
> Unhandled error for request GET /api/plants/plantMeterNo/99-99-9999-99-9?token=site_token_for_cloud_jointer: [object Object]
> Unhandled error for request GET /api/plants/plantMeterNo/99-99-9999-99-9?token=site_token_for_cloud_jointer: [object Object]
> Unhandled error for request GET /api/plants/plantMeterNo/99-99-9999-99-9?token=site_token_for_cloud_jointer: TypeError: Cannot read property 'id' of null
>     at Function.Plant.plantMeterNo (/rest-api-dreams/common/models/plant.js:42:43)
> Unhandled error for request GET /api/plants/plantMeterNo/99-99-9999-99-9?token=site_token_for_cloud_jointer: TypeError: Cannot read property 'id' of null
>     at Function.Plant.plantMeterNo (/rest-api-dreams/common/models/plant.js:42:43)
> Unhandled error for request GET /api/plants/plantMeterNo/99-99-9999-99-9?token=site_token_for_cloud_jointer: [object Object]
> Unhandled error for request GET /api/plants/plantMeterNo/99-99-9999-99-9?token=site_token_for_cloud_jointer: TypeError: Cannot read property 'id' of null
>     at Function.Plant.plantMeterNo (/rest-api-dreams/common/models/plant.js:42:43)
> datasources.local.json already exists
> 
> > loopback-getting-started@1.0.0 start-nossl /rest-api-dreams
> > cross-env NODE_ENV=production node .
> 
> Plants settings.validateUpsert was overriden to false
> Unhandled error for request GET /api/plants/plantMeterNo/99-99-9999-99-9?token=site_token_for_cloud_jointer: TypeError: Cannot read property 'id' of null
>     at Function.Plant.plantMeterNo (/rest-api-dreams/common/models/plant.js:42:43)
> Unhandled error for request GET /api/plants/plantMeterNo/99-99-9999-99-9?token=site_token_for_cloud_jointer: TypeError: Cannot read property 'id' of null
>     at Function.Plant.plantMeterNo (/rest-api-dreams/common/models/plant.js:42:43)
> 

但手動填址是可正常連線的.

![連線成功](https://user-images.githubusercontent.com/42212961/106075457-9fb65b80-6148-11eb-9590-07ca6c696b8b.png)

昨日(1/27)已試過最新版Code, 砍Image砍Container重拉重Build, WebAPI還是相同錯誤.

![docker_images](https://user-images.githubusercontent.com/42212961/106076860-63382f00-614b-11eb-933a-811dd67b5f3a.png)

我搞錯什麼了嗎?

**Comment by taipower-dreams-tester** [comment]
您好，
請檢查一下MySQL裡面dreams_business.AccessToken這個table裡面是否有一筆id是site_token_for_cloud_jointer的資料。通常他會在程式正常啟動後被生成，如果沒有請手動加上。

**Comment by MKTtoolman** [comment]
dreams_business.AccessToken已檢查, 是有此id的.
 > ![AccessToken](https://user-images.githubusercontent.com/42212961/106098984-ee79ea80-6174-11eb-912d-4a25d303589b.png)

附上dreams_business.Gateway, 有請檢查是否正常, 感謝.
> ![Gateway](https://user-images.githubusercontent.com/42212961/106098988-f0dc4480-6174-11eb-85fe-6628ca131798.png)

**Comment by taipower-dreams-tester** [comment]
您好，
台電的規範文件上可能沒有更新到，請將API網址從:
https://172.16.1.131/api/plants/plantMeterNo/99-99-9999-99-9?token=site_token_for_cloud_jointer
改成
https://172.16.1.131/api/Plants/plantMeterNo/99-99-9999-99-9?access_token=site_token_for_cloud_jointer
試試看

謝謝!

**Comment by MKTtoolman** [comment]
確認一下測試需求, dream server是否dnp3 address固定為3, 亦或須依現場調整?

**Comment by taipower-dreams-tester** [comment]
您好，目前固定是3喔
