### ISSUE TITLE
關於3-8伺服器現場設定功率的Dead Band閥值為2.5%問題

### ISSUE THREAD

**Issue by cloudesyu** [taipower-dreams-tester/dreams-cloud-joint-tester#13]
請問3-8 需回傳哪一個欄位值為250？
我試過
功率因數 9 
功率因數觸發Dead Band回傳的設定值 29
皆不行

能否告知確切的點位、謝謝。

**Comment by taipower-dreams-tester** [comment]
您好，
這裡是指「功率」的deadband閥值，不是「功率因數」，因此確切的點位是27喔。

**Comment by cloudesyu** [comment]
了解，已驗證、謝謝您。
