### ISSUE TITLE
[3-1] 請問10秒timeout, 是以什麼為依據?

### ISSUE THREAD

**Issue by MKTtoolman** [taipower-dreams-tester/dreams-cloud-joint-tester#14]
1. dreams server 的 dnp3-master 看起來也收到了. 但不知因何條件? Web 判 timeout.

![3-1_Test](https://user-images.githubusercontent.com/42212961/107321996-8dd89f00-6ade-11eb-87bf-1ed4296ffc28.gif)

2. 另外3系列, 單一測項 Select/Operate 和 Direct operate 指令, 是會一起傳嗎?
    Direct operate 的 Qual Codes 似乎怪怪的.
    我們有要支援此指令 [ object: 41, variation: 2, func code(dec.): 5(direct operate), qualifier field(hex.): 6(no range field) ] 嗎?
    3-*系列 好像都有此現象.

**hint**: 左上圖是 dreams server 的 dnp3-master log

**Comment by taipower-dreams-tester** [comment]
您好，
1. 取消變流器自主調控成功之後，點位18因狀態改變應有deadband回傳。請確認是否有正常回傳。
![2021-02-12_09h50_26](https://user-images.githubusercontent.com/76514336/107721551-dcbd4900-6d17-11eb-8820-a24fc737f7d9.png)
2. 是的，會一起傳。Qualifier Field的部分規範中並未明確指定，因此該值僅為目前實作，如果有實行上的困難還請提出討論。
