### ISSUE TITLE
關於1-1連線受測資料系統

### ISSUE THREAD

**Issue by hoyuisun** [taipower-dreams-tester/dreams-cloud-joint-tester#15]
不好意思，請問一下，此項Dreams平台怎麼驗證成功連線受測資料系統
telnet受測資料系統的port是有通的，但Dreams模擬伺服器皆顯示不通過
再麻煩大家解惑，謝謝

**Comment by hoyuisun** [comment]
研究一下，需對模擬平台的資料庫寫入對應電號的發電資料，才算通過
因此，想請教大家要怎麼對模擬平台做寫入數值的動作，謝謝！
![Uploading Screen Shot 2021-02-20 at 4.52.04 PM.png…]()

**Comment by hoyuisun** [comment]
已解決，謝謝

**Comment by jp4jp4wu6** [comment]
> 不好意思，請問一下，此項Dreams平台怎麼驗證成功連線受測資料系統
> telnet受測資料系統的port是有通的，但Dreams模擬伺服器皆顯示不通過
> 再麻煩大家解惑，謝謝

請問這裡是如何解決的??
感謝你的回覆。

**Comment by hoyuisun** [comment]
Dreams測試平台會主動做polling，你response回去後，資料庫有值就會PASS
換句話說，這個測試項目非去檢測雲端平台的狀態，是檢查資料庫有沒有資料
此測試在一開始填入IP & PORT後會去做polling
因為我一開始只是想說這項只是測連線，所以都沒吐東西回去，後來有吐回去就正常了

**Comment by jp4jp4wu6** [comment]
> Dreams測試平台會主動做polling，你response回去後，資料庫有值就會PASS
> 換句話說，這個測試項目非去檢測雲端平台的狀態，是檢查資料庫有沒有資料
> 此測試在一開始填入IP & PORT後會去做polling
> 因為我一開始只是想說這項只是測連線，所以都沒吐東西回去，後來有吐回去就正常了

非常感謝回覆。

outstation 是如何response，如果以dnp3方式回傳是怎麼樣的格式?
另外，在我填入IP & port送出之前，無法從API取得電號，這樣正常嗎?
請問你是用opendnp3java介面與DREAMS做溝通嗎?

剛入門，很多概念不是很懂，還請協助，
再次感謝hoyuisun撥空回覆。

**Comment by hoyuisun** [comment]
1.對的，如先前議題提到的，此測試平台一次僅提供一人使用，所以在妳離開(關閉)測試平台，會將資料庫資料清除
因此，有機率有時會沒清乾淨，就會發生提到的案場電號已存在問題#1，要送出後，才會進行註冊，API才能取得
只是現階段其實都是固定的，即master必為3，slave必為4跟5

2.沒有透過第三方DNP library，是自己解析/組DNP3封包進行傳遞

3.根據近幾禮拜測試，在初始化測試的時候會有以下動作，有下列動作的request/response，理論上1-1、1-2就能通過
Step 1. Disable unsolicited message [master: 3, slave: 4], then response
Step 2. Disable unsolicited message [master: 3, slave: 5], then response
Step 3. Write Internal indication (IIN), then response
Step 4. Enable unsolicited message [master: 3, slave: 4], then response
Step 5. Enable unsolicited message [master: 3, slave: 5], then response
Step 6. Read class 1, 2, 3, 0 [master: 3, slave: 4], then response
Step 7. Read class 1, 2, 3, 0 [master: 3, slave: 5], then response

其中，Step 6、Step 7的資料我猜就是1-2測試資料的內容，還請參考！

**Comment by jp4jp4wu6** [comment]
> 2.沒有透過第三方DNP library，是自己解析/組DNP3封包進行傳遞

DNP3傳遞的內容是如何組，是否有實例可了解??例如1-1的response

> Dreams測試平台會主動做polling，你response回去後，資料庫有值就會PASS
> 換句話說，這個測試項目非去檢測雲端平台的狀態，是檢查資料庫有沒有資料

這裡的檢查資料庫有沒有資料，是指outstation要有資料庫?還是DREAMS的mysql

感謝hoyuisun撥空回覆。

**Comment by hoyuisun** [comment]
1. 要去看DNP3 Protocol，若單純看封包可以參考OpenDNP3提供的內容: https://dnp3.github.io/conformance/report.html
若以測試1-1的來看，可以參考這邊的內容: https://dnp3.github.io/conformance/8.5.5.2.2/log.html
dnp master會丟類似05 64 14 C4 00 04 01 00 E9 B6 C0 C1 01 3C 02 06 3C 03 06 3C 04 06 3C 01 06 7A 6F
你要分別response group 60的內容

2.資料庫是指dreams mysql

**Comment by hoyuisun** [comment]
我是用Dbeaver這套軟體，供參考

**Comment by jp4jp4wu6** [comment]
> 我是用Dbeaver這套軟體，供參考

非常感謝你的回覆，因為對sql太不熟，經了解後已經理解如何操作。

> Dreams測試平台會主動做polling，你response回去後，資料庫有值就會PASS
> 換句話說，這個測試項目非去檢測雲端平台的狀態，是檢查資料庫有沒有資料
> 此測試在一開始填入IP & PORT後會去做polling
> 因為我一開始只是想說這項只是測連線，所以都沒吐東西回去，後來有吐回去就正常了

1-1點擊按鈕後，如下圖，像是會去資料表找資料。
![image](https://user-images.githubusercontent.com/79955266/110906462-efdb2d00-8346-11eb-8d99-b2e367c7f1fb.png)

資料表中目前無資料。
![image](https://user-images.githubusercontent.com/79955266/110908213-7264ec00-8349-11eb-99f9-da530111e814.png)

https://github.com/taipower-dreams-tester/dreams-cloud-joint-tester/blob/985890d259169c5807a0b76b43ad85adb798c9e8/tester-web/cloud-joint-tester-web/src/containers/testContents/TestOneOne.js#L38
從code中查找，看不出api要的是什麼。

隨意塞資料後，還是未能通過。
不知道理解的是否正確?? 如果正確，api要的是什麼呢?


再次感謝hoyuisun撥空回覆。

**Comment by hoyuisun** [comment]
PlantNo數值要對應你看到的99-99-9999-99-9那兩個內容，相符才會PASS

**Comment by jp4jp4wu6** [comment]
> PlantNo數值要對應你看到的99-99-9999-99-9那兩個內容，相符才會PASS

照上述帶入資料後，確實通過了。
非常感謝hoyuisun的撥空回覆。

**Comment by jp4jp4wu6** [comment]
> PlantNo數值要對應你看到的99-99-9999-99-9那兩個內容，相符才會PASS

手動帶入資料後，確實1-1,1-2通過了。
這樣看來應該是填完IP & port送出，DREAMS測試平台主動做polling，
outstation 就要回應這兩筆資料，DREAMS就會先存入這兩筆資料。

不知道以上理解是否正確??

這樣就回到測試localhost port有通，本機opendnp3 master對outstation連得上，
而DREAMS一樣在本機 polling，outstation卻沒反應。

> 不好意思，請問一下，此項Dreams平台怎麼驗證成功連線受測資料系統
> telnet受測資料系統的port是有通的，但Dreams模擬伺服器皆顯示不通過
> 再麻煩大家解惑，謝謝

再次感謝hoyuisun撥空回覆。

**Comment by hoyuisun** [comment]
> > PlantNo數值要對應你看到的99-99-9999-99-9那兩個內容，相符才會PASS
> 
> 手動帶入資料後，確實1-1,1-2通過了。
> 這樣看來應該是填完IP & port送出，DREAMS測試平台主動做polling，
> outstation 就要回應這兩筆資料，DREAMS就會先存入這兩筆資料。
> 
> 不知道以上理解是否正確??

對的，連上後會主動polling slave 4&5，以取得各outstation資料

**Comment by jp4jp4wu6** [comment]
https://github.com/taipower-dreams-tester/dreams-cloud-joint-tester/issues/26#issuecomment-799073351

你好，
原本是這樣的思維，因DREAMS與openDNP3預設是20000port，
沒做更改的情況下，DREAMS應該會嘗試與20000port的outstation做連線，
但納悶的是不見DREAMS有做溝通的跡象，而用其他軟體測試20000port，outstation會有反應。
以上皆在本機做測試，目前還在找解決辦法。

想請教大家有什麼建議方法或有什麼要注意的地方。
