### ISSUE TITLE
[2-1] timeOut, 超過 10 秒未拿到資料

### ISSUE THREAD

**Issue by hoyuisun** [taipower-dreams-tester/dreams-cloud-joint-tester#16]
請問一下，查看dreams master log，以及資料庫都有拿到數值，為何網頁會呈現timeout，謝謝
<img width="931" alt="Screen Shot 2021-02-23 at 11 50 48 AM" src="https://user-images.githubusercontent.com/4025334/108808128-df098800-75e0-11eb-9e93-fb9e1ee6b6fa.png">

查看log跟用postman去看資料
<img width="1302" alt="Screen Shot 2021-02-23 at 11 48 15 AM" src="https://user-images.githubusercontent.com/4025334/108807990-90f48480-75e0-11eb-9797-024a5dc9306e.png">
<img width="881" alt="Screen Shot 2021-02-23 at 11 47 30 AM" src="https://user-images.githubusercontent.com/4025334/108808026-9e117380-75e0-11eb-9913-ba792d7753be.png">

且透過wireshark查看封包也是有response回應的
<img width="1408" alt="Screen Shot 2021-02-23 at 11 50 01 AM" src="https://user-images.githubusercontent.com/4025334/108808053-b2557080-75e0-11eb-8182-3a3ae8429464.png">

**Comment by taipower-dreams-tester** [comment]
您好，
不好意思花了一點時間釐清。
您帶上來的timestamp點位(點位32)應該要是時間戳，也就是要跟你圖上帶的時間戳1614051792一致。

**Comment by hoyuisun** [comment]
了解，我再試看看，感謝！

**Comment by hoyuisun** [comment]
不好意思，改成timestamp為時間戳，有時會成功顯示詢問結果，但也有未回應的情況，還有其他因素嗎...?
<img width="341" alt="Screen Shot 2021-02-25 at 3 48 41 PM" src="https://user-images.githubusercontent.com/4025334/109120572-17e06300-7781-11eb-9227-21a3b03f78d4.png">

**Comment by hoyuisun** [comment]
補充一下，我透過Postman抓取的資訊跟wireshark封包，後來在測試幾次，都沒有在顯示出來...
下方資訊皆是按下2-1 Polling後得到的資訊
<img width="827" alt="Screen Shot 2021-02-26 at 11 20 16 AM" src="https://user-images.githubusercontent.com/4025334/109250615-ede07c80-7824-11eb-8df6-1c803373a1b2.png">
<img width="349" alt="Screen Shot 2021-02-26 at 11 20 58 AM" src="https://user-images.githubusercontent.com/4025334/109250639-f5078a80-7824-11eb-9b82-35f1352af300.png">

**Comment by taipower-dreams-tester** [comment]
您好，
請確認測試程式所在機器跟您的雲端伺服器兩邊的系統時間都是有校準且同步的。
atTimestamp是測試程式收到資料時的本機時間，itemTimestamp是點位32指定的時間戳(應該為雲端系統取得資料時的採樣時間)，因此itemTimestamp比atTimestamp超前44秒是不太合理的。

**Comment by hoyuisun** [comment]
了解，另外想請教，例如我發出Polling要求，從wireshark有收到相關封包的request跟response
但看雲端伺服器的Log是沒有顯示有送出此polling的紀錄，在這種情況下，都會timeout(但wireshark是有正常的收送紀錄)
得將docker重啟，才有機率性polling會成功，想問有什麼原因會導致這個問題，謝謝

**Comment by taipower-dreams-tester** [comment]
您好，
雲端伺服器指的是受測的雲端系統，也就是outstation端嗎? 因為polling應該是由master端送出才對。
另外您重啟的是哪一個docker呢? 如果是dnp3-master，原本他重啟之後就會嘗試polling所有outstation喔。
最後還要請您確認一下測試程式是否安裝在Ubuntu的機器。
目前由測試程式下polling會經過API server，走docker之間的socket將指令傳給dnp3-master，而docker socket這一段目前的程式只適用於Ubuntu機器喔。

**Comment by hoyuisun** [comment]
不好意思，雲端伺服器我這邊是指測試平台(master);重啟dnp3-master沒錯
換個說法，我在測試平台(master)點選2-1的polling，從wireshark中有看到read, Class 0123以及response
理論上成功的話，在測試平台會看到Manually perform integrity poll的相關Log訊息，但是其結果沒有
遇到此類現象，我會先重啟dnp3-master docker以及測試平台網頁，有機率性會讓我polling成功

**Comment by hoyuisun** [comment]
再補充一下，目前測試下來，如果從測試平台填入IP、Port進行測試，依序執行，這樣沒問題
話個說法，一進去先執行2-1是可以正常運作的，但是執行2-1後去執行3-2、3-3等測試項目再回去執行2-1就都會timeout了
或者，我一進去先執行3-2項目，再去執行2-1項目，這樣也會得到timeout結果
想問這樣是否是正常的，謝謝

**Comment by taipower-dreams-tester** [comment]
您好，
經過驗證，我們這邊無法複製您所說的狀況。
請問是執行完3-2之後再執行2-1，就不會出現Manually perform integrity poll了嗎?
如果沒有看到該log代表API server無法正常將指令傳遞給dnp3-master，可能要看一下是否有任何錯誤訊息。

**Comment by hoyuisun** [comment]
對的，再經過測試，應該說當我有回傳deaband回去的時候，再做2-1 polling動作，之後都會出現timeout
看wireshark是有傳送read 0123也有response，下列為填入ip測試，問兩次polling後，調整數值觸發deadband，後續2-1 polling後數值都不會在這邊查詢到，log也沒顯示Manually perform integrity poll紀錄
想問錯誤訊息要去哪邊查看，謝謝！
[
    {
        "plantNo": "99-99-9999-99-9",
        "currentPhaseA": 15,
        "currentPhaseB": 10,
        "currentPhaseC": 1,
        "currentPhaseN": 1,
        "voltagePhaseA": 2,
        "voltagePhaseB": 2,
        "voltagePhaseC": 2,
        "P_SUM": 0.08,
        "Q_SUM": 0.09,
        "PF_AVG": 0.9,
        "frequency": 60,
        "total_kWh": 0,
        "irradiance": 90,
        "wind_speed": 90,
        "PF_setting": 90,
        "P_setting": 80,
        "Q_setting": 0,
        "vpset_setting": 105,
        "control_result_01_25": 0,
        "control_result_26_50": 0,
        "currentPhaseA_deadband": 0.05,
        "currentPhaseB_deadband": 0.05,
        "currentPhaseC_deadband": 0.05,
        "currentPhaseN_deadband": 0.05,
        "voltagePhaseA_deadband": 0.01,
        "voltagePhaseB_deadband": 0.01,
        "voltagePhaseC_deadband": 0.01,
        "P_SUM_deadband": 0.025,
        "Q_SUM_deadband": 0.05,
        "PF_AVG_deadband": 0.01,
        "frequency_deadband": 0.005,
        "total_kWh_deadband": 0,
        "itemTimestamp": 1614829199,
        "atTimestamp": 1614829201,
        "id": 1152
    },
    {
        "plantNo": "99-99-9999-99-9",
        "currentPhaseA": 15,
        "currentPhaseB": 10,
        "currentPhaseC": 1,
        "currentPhaseN": 1,
        "voltagePhaseA": 2,
        "voltagePhaseB": 2,
        "voltagePhaseC": 2,
        "P_SUM": 0.08,
        "Q_SUM": 0.09,
        "PF_AVG": 0.9,
        "frequency": 60,
        "total_kWh": 0,
        "irradiance": 90,
        "wind_speed": 90,
        "PF_setting": 90,
        "P_setting": 80,
        "Q_setting": 0,
        "vpset_setting": 105,
        "control_result_01_25": 0,
        "control_result_26_50": 0,
        "currentPhaseA_deadband": 0.05,
        "currentPhaseB_deadband": 0.05,
        "currentPhaseC_deadband": 0.05,
        "currentPhaseN_deadband": 0.05,
        "voltagePhaseA_deadband": 0.01,
        "voltagePhaseB_deadband": 0.01,
        "voltagePhaseC_deadband": 0.01,
        "P_SUM_deadband": 0.025,
        "Q_SUM_deadband": 0.05,
        "PF_AVG_deadband": 0.01,
        "frequency_deadband": 0.005,
        "total_kWh_deadband": 0,
        "itemTimestamp": 1614829199,
        "atTimestamp": 1614829201,
        "id": 1153
    },
    {
        "plantNo": "88-88-8888-88-8",
        "currentPhaseA": 15,
        "currentPhaseB": 10,
        "currentPhaseC": 1,
        "currentPhaseN": 1,
        "voltagePhaseA": 2,
        "voltagePhaseB": 2,
        "voltagePhaseC": 2,
        "P_SUM": 0.08,
        "Q_SUM": 0.09,
        "PF_AVG": 0.9,
        "frequency": 60,
        "total_kWh": 0,
        "irradiance": 90,
        "wind_speed": 90,
        "PF_setting": 90,
        "P_setting": 80,
        "Q_setting": 0,
        "vpset_setting": 105,
        "control_result_01_25": 0,
        "control_result_26_50": 0,
        "currentPhaseA_deadband": 0.05,
        "currentPhaseB_deadband": 0.05,
        "currentPhaseC_deadband": 0.05,
        "currentPhaseN_deadband": 0.05,
        "voltagePhaseA_deadband": 0.01,
        "voltagePhaseB_deadband": 0.01,
        "voltagePhaseC_deadband": 0.01,
        "P_SUM_deadband": 0.025,
        "Q_SUM_deadband": 0.05,
        "PF_AVG_deadband": 0.01,
        "frequency_deadband": 0.005,
        "total_kWh_deadband": 0,
        "itemTimestamp": 1614829196,
        "atTimestamp": 1614829201,
        "id": 1154
    },
    {
        "plantNo": "88-88-8888-88-8",
        "currentPhaseA": 15,
        "currentPhaseB": 10,
        "currentPhaseC": 1,
        "currentPhaseN": 1,
        "voltagePhaseA": 2,
        "voltagePhaseB": 2,
        "voltagePhaseC": 2,
        "P_SUM": 0.08,
        "Q_SUM": 0.09,
        "PF_AVG": 0.9,
        "frequency": 60,
        "total_kWh": 0,
        "irradiance": 90,
        "wind_speed": 90,
        "PF_setting": 90,
        "P_setting": 80,
        "Q_setting": 0,
        "vpset_setting": 105,
        "control_result_01_25": 0,
        "control_result_26_50": 0,
        "currentPhaseA_deadband": 0.05,
        "currentPhaseB_deadband": 0.05,
        "currentPhaseC_deadband": 0.05,
        "currentPhaseN_deadband": 0.05,
        "voltagePhaseA_deadband": 0.01,
        "voltagePhaseB_deadband": 0.01,
        "voltagePhaseC_deadband": 0.01,
        "P_SUM_deadband": 0.025,
        "Q_SUM_deadband": 0.05,
        "PF_AVG_deadband": 0.01,
        "frequency_deadband": 0.005,
        "total_kWh_deadband": 0,
        "itemTimestamp": 1614829196,
        "atTimestamp": 1614829201,
        "id": 1155
    },
    {
        "plantNo": "88-88-8888-88-8",
        "currentPhaseA": 15,
        "currentPhaseB": 10,
        "currentPhaseC": 1,
        "currentPhaseN": 1,
        "voltagePhaseA": 2,
        "voltagePhaseB": 2,
        "voltagePhaseC": 2,
        "P_SUM": 0.08,
        "Q_SUM": 0.09,
        "PF_AVG": 0.9,
        "frequency": 60,
        "total_kWh": 0,
        "irradiance": 90,
        "wind_speed": 90,
        "PF_setting": 90,
        "P_setting": 80,
        "Q_setting": 0,
        "vpset_setting": 105,
        "control_result_01_25": 0,
        "control_result_26_50": 0,
        "currentPhaseA_deadband": 0.05,
        "currentPhaseB_deadband": 0.05,
        "currentPhaseC_deadband": 0.05,
        "currentPhaseN_deadband": 0.05,
        "voltagePhaseA_deadband": 0.01,
        "voltagePhaseB_deadband": 0.01,
        "voltagePhaseC_deadband": 0.01,
        "P_SUM_deadband": 0.025,
        "Q_SUM_deadband": 0.05,
        "PF_AVG_deadband": 0.01,
        "frequency_deadband": 0.005,
        "total_kWh_deadband": 0,
        "itemTimestamp": 1614829196,
        "atTimestamp": 1614829201,
        "id": 1156
    },
    {
        "plantNo": "88-88-8888-88-8",
        "currentPhaseA": 15,
        "currentPhaseB": 10,
        "currentPhaseC": 1,
        "currentPhaseN": 1,
        "voltagePhaseA": 2,
        "voltagePhaseB": 2,
        "voltagePhaseC": 2,
        "P_SUM": 0.08,
        "Q_SUM": 0.09,
        "PF_AVG": 0.9,
        "frequency": 60,
        "total_kWh": 0,
        "irradiance": 90,
        "wind_speed": 90,
        "PF_setting": 90,
        "P_setting": 80,
        "Q_setting": 0,
        "vpset_setting": 105,
        "control_result_01_25": 0,
        "control_result_26_50": 0,
        "currentPhaseA_deadband": 0.05,
        "currentPhaseB_deadband": 0.05,
        "currentPhaseC_deadband": 0.05,
        "currentPhaseN_deadband": 0.05,
        "voltagePhaseA_deadband": 0.01,
        "voltagePhaseB_deadband": 0.01,
        "voltagePhaseC_deadband": 0.01,
        "P_SUM_deadband": 0.025,
        "Q_SUM_deadband": 0.05,
        "PF_AVG_deadband": 0.01,
        "frequency_deadband": 0.005,
        "total_kWh_deadband": 0,
        "itemTimestamp": 1614829196,
        "atTimestamp": 1614829201,
        "id": 1157
    },
    {
        "plantNo": "99-99-9999-99-9",
        "currentPhaseA": 15,
        "currentPhaseB": 10,
        "currentPhaseC": 1,
        "currentPhaseN": 1,
        "voltagePhaseA": 2,
        "voltagePhaseB": 2,
        "voltagePhaseC": 2,
        "P_SUM": 0.08,
        "Q_SUM": 0.09,
        "PF_AVG": 0.9,
        "frequency": 60,
        "total_kWh": 0,
        "irradiance": 90,
        "wind_speed": 90,
        "PF_setting": 90,
        "P_setting": 80,
        "Q_setting": 0,
        "vpset_setting": 105,
        "control_result_01_25": 0,
        "control_result_26_50": 0,
        "currentPhaseA_deadband": 0.05,
        "currentPhaseB_deadband": 0.05,
        "currentPhaseC_deadband": 0.05,
        "currentPhaseN_deadband": 0.05,
        "voltagePhaseA_deadband": 0.01,
        "voltagePhaseB_deadband": 0.01,
        "voltagePhaseC_deadband": 0.01,
        "P_SUM_deadband": 0.025,
        "Q_SUM_deadband": 0.05,
        "PF_AVG_deadband": 0.01,
        "frequency_deadband": 0.005,
        "total_kWh_deadband": 0,
        "itemTimestamp": 1614829220,
        "atTimestamp": 1614829221,
        "id": 1158
    },
    {
        "plantNo": "99-99-9999-99-9",
        "currentPhaseA": 15,
        "currentPhaseB": 10,
        "currentPhaseC": 1,
        "currentPhaseN": 1,
        "voltagePhaseA": 2,
        "voltagePhaseB": 2,
        "voltagePhaseC": 2,
        "P_SUM": 0.08,
        "Q_SUM": 0.09,
        "PF_AVG": 0.9,
        "frequency": 60,
        "total_kWh": 0,
        "irradiance": 90,
        "wind_speed": 90,
        "PF_setting": 90,
        "P_setting": 80,
        "Q_setting": 0,
        "vpset_setting": 105,
        "control_result_01_25": 0,
        "control_result_26_50": 0,
        "currentPhaseA_deadband": 0.05,
        "currentPhaseB_deadband": 0.05,
        "currentPhaseC_deadband": 0.05,
        "currentPhaseN_deadband": 0.05,
        "voltagePhaseA_deadband": 0.01,
        "voltagePhaseB_deadband": 0.01,
        "voltagePhaseC_deadband": 0.01,
        "P_SUM_deadband": 0.025,
        "Q_SUM_deadband": 0.05,
        "PF_AVG_deadband": 0.01,
        "frequency_deadband": 0.005,
        "total_kWh_deadband": 0,
        "itemTimestamp": 1614829220,
        "atTimestamp": 1614829221,
        "id": 1159
    },
    {
        "plantNo": "99-99-9999-99-9",
        "currentPhaseA": 15,
        "currentPhaseB": 10,
        "currentPhaseC": 1,
        "currentPhaseN": 1,
        "voltagePhaseA": 2,
        "voltagePhaseB": 2,
        "voltagePhaseC": 2,
        "P_SUM": 0.08,
        "Q_SUM": 0.09,
        "PF_AVG": 0.9,
        "frequency": 60,
        "total_kWh": 0,
        "irradiance": 90,
        "wind_speed": 90,
        "PF_setting": 90,
        "P_setting": 80,
        "Q_setting": 0,
        "vpset_setting": 105,
        "control_result_01_25": 0,
        "control_result_26_50": 0,
        "currentPhaseA_deadband": 0.05,
        "currentPhaseB_deadband": 0.05,
        "currentPhaseC_deadband": 0.05,
        "currentPhaseN_deadband": 0.05,
        "voltagePhaseA_deadband": 0.01,
        "voltagePhaseB_deadband": 0.01,
        "voltagePhaseC_deadband": 0.01,
        "P_SUM_deadband": 0.025,
        "Q_SUM_deadband": 0.05,
        "PF_AVG_deadband": 0.01,
        "frequency_deadband": 0.005,
        "total_kWh_deadband": 0,
        "itemTimestamp": 1614829252,
        "atTimestamp": 1614829254,
        "id": 1160
    },
    {
        "plantNo": "99-99-9999-99-9",
        "currentPhaseA": 15,
        "currentPhaseB": 10,
        "currentPhaseC": 1,
        "currentPhaseN": 1,
        "voltagePhaseA": 2,
        "voltagePhaseB": 2,
        "voltagePhaseC": 2,
        "P_SUM": 0.08,
        "Q_SUM": 0.09,
        "PF_AVG": 0.9,
        "frequency": 60,
        "total_kWh": 0,
        "irradiance": 90,
        "wind_speed": 90,
        "PF_setting": 90,
        "P_setting": 80,
        "Q_setting": 0,
        "vpset_setting": 105,
        "control_result_01_25": 0,
        "control_result_26_50": 0,
        "currentPhaseA_deadband": 0.05,
        "currentPhaseB_deadband": 0.05,
        "currentPhaseC_deadband": 0.05,
        "currentPhaseN_deadband": 0.05,
        "voltagePhaseA_deadband": 0.01,
        "voltagePhaseB_deadband": 0.01,
        "voltagePhaseC_deadband": 0.01,
        "P_SUM_deadband": 0.025,
        "Q_SUM_deadband": 0.05,
        "PF_AVG_deadband": 0.01,
        "frequency_deadband": 0.005,
        "total_kWh_deadband": 0,
        "itemTimestamp": 1614829252,
        "atTimestamp": 1614829254,
        "id": 1161
    },
    {
        "plantNo": "88-88-8888-88-8",
        "currentPhaseA": 16,
        "currentPhaseB": null,
        "currentPhaseC": null,
        "currentPhaseN": null,
        "voltagePhaseA": null,
        "voltagePhaseB": null,
        "voltagePhaseC": null,
        "P_SUM": null,
        "Q_SUM": null,
        "PF_AVG": null,
        "frequency": null,
        "total_kWh": null,
        "irradiance": null,
        "wind_speed": null,
        "PF_setting": null,
        "P_setting": null,
        "Q_setting": null,
        "vpset_setting": null,
        "control_result_01_25": null,
        "control_result_26_50": null,
        "currentPhaseA_deadband": null,
        "currentPhaseB_deadband": null,
        "currentPhaseC_deadband": null,
        "currentPhaseN_deadband": null,
        "voltagePhaseA_deadband": null,
        "voltagePhaseB_deadband": null,
        "voltagePhaseC_deadband": null,
        "P_SUM_deadband": null,
        "Q_SUM_deadband": null,
        "PF_AVG_deadband": null,
        "frequency_deadband": null,
        "total_kWh_deadband": null,
        "itemTimestamp": 1614829298,
        "atTimestamp": 1614829298,
        "id": 1162
    },
    {
        "plantNo": "99-99-9999-99-9",
        "currentPhaseA": 16,
        "currentPhaseB": null,
        "currentPhaseC": null,
        "currentPhaseN": null,
        "voltagePhaseA": null,
        "voltagePhaseB": null,
        "voltagePhaseC": null,
        "P_SUM": null,
        "Q_SUM": null,
        "PF_AVG": null,
        "frequency": null,
        "total_kWh": null,
        "irradiance": null,
        "wind_speed": null,
        "PF_setting": null,
        "P_setting": null,
        "Q_setting": null,
        "vpset_setting": null,
        "control_result_01_25": null,
        "control_result_26_50": null,
        "currentPhaseA_deadband": null,
        "currentPhaseB_deadband": null,
        "currentPhaseC_deadband": null,
        "currentPhaseN_deadband": null,
        "voltagePhaseA_deadband": null,
        "voltagePhaseB_deadband": null,
        "voltagePhaseC_deadband": null,
        "P_SUM_deadband": null,
        "Q_SUM_deadband": null,
        "PF_AVG_deadband": null,
        "frequency_deadband": null,
        "total_kWh_deadband": null,
        "itemTimestamp": 1614829299,
        "atTimestamp": 1614829299,
        "id": 1163
    }
]

**Comment by hoyuisun** [comment]
補個log
<img width="1246" alt="Screen Shot 2021-03-04 at 11 55 19 AM" src="https://user-images.githubusercontent.com/4025334/109909154-90df3d80-7ce0-11eb-8ff9-d62af9554510.png">

**Comment by hoyuisun** [comment]
你好，經過多次測試，我得到的結論是Dreams測試系統有回Confirm(ACK)給雲端平台後，再去Polling都會timeout
換句話說，unsolicited message or change of state (deadband event)觸發後，再執行polling都會timeout

有故意將deadband事件改成0x81回傳，Dreams測試系統沒有回confirm，這樣polling還是正常的
改為0x82後，Dreams測試系統回confirm，polling就會timeout(但是wireshark確定有送收封包的)

在此情況下，查看wireshark都是有正常去送跟收封包，理論上polling完後，應該會把資料寫入資料庫
我觀察是沒有寫入資料庫，導致timeout，因此，想問這類問題要怎麼解決？
雖然不影響測試，只是不太理解為何會這樣，謝謝

**Comment by taipower-dreams-tester** [comment]
您好，
您可以參考這一段code:
https://github.com/taipower-dreams-tester/dreams-cloud-joint-tester/blob/4b1a7f37597c4aa383fc4176dcbb299e694de748/dnp3-master/dreams-master/src/dreams-master/main.cpp#L157

基本上DREAMS測試系統的 DNP3 master在做完一些基本配置之後就會進入這個迴圈，不停地檢查是否有新的指令進來(控制或是polling)。依照您的描述猜測應該是DREAMS測試系統在回完confirm之後在這個迴圈的某一個步驟卡住了，導致它無法再接收新的指令，因此也無法印出"Manually perform integrity poll"的log。

由於我們無法複製您所說的情形，這邊就要麻煩您在迴圈當中加log，或是使用GDB等工具以確認是否卡住以及卡在哪一步了。

**Comment by hoyuisun** [comment]
可以請教你們測試，Dreams測試平台是有回Confirm的嗎?

**Comment by taipower-dreams-tester** [comment]
DREAMS測試平台的原始碼和這個repository是同步更新的，您可以使用這邊的repository進行測試。

另外如果問題已經解決，還煩請將issue關閉，感謝!
