### ISSUE TITLE
[2-4]定時完整資料主動上傳

### ISSUE THREAD

**Issue by hoyuisun** [taipower-dreams-tester/dreams-cloud-joint-tester#17]
不好意思，觀察wireshark有收到dreams回傳的Ack，但平台仍顯示距離取得資料 timeout 尚餘：XX分鐘 XX 秒，想請教這個測項會做什麼判斷...
<img width="960" alt="Screen Shot 2021-02-25 at 3 16 16 PM" src="https://user-images.githubusercontent.com/4025334/109117799-6db30c00-777d-11eb-8c45-cf5c8c8bcc49.png">
<img width="920" alt="Screen Shot 2021-02-25 at 3 16 29 PM" src="https://user-images.githubusercontent.com/4025334/109117845-7c99be80-777d-11eb-82f0-04b2be40eb85.png">

**Comment by taipower-dreams-tester** [comment]
您好，
此測項旨在檢查按下開始測試後15分鐘內，可控及不可控兩個案場是否都有回傳所有點位都有值的完整資料。
