### ISSUE TITLE
[2-3] 2-3提升變流器輸出電流- 通過的基準

### ISSUE THREAD

**Issue by hoyuisun** [taipower-dreams-tester/dreams-cloud-joint-tester#21]
不好意思，想請教其測試結果為下圖，要如何檢驗是否符合通過驗證
<img width="935" alt="Screen Shot 2021-03-02 at 2 53 55 PM" src="https://user-images.githubusercontent.com/4025334/109611306-fe685e00-7b68-11eb-8ce4-2bcb304db348.png">

**Comment by taipower-dreams-tester** [comment]
您好，
實際測試時工研院會備有模擬器材，需驗證：
1. 模擬器材顯示數值變動超過規定百分比時，測試程式應收到deadband回傳。
2. 測試程式所收到之電流值與模擬器材顯示數值相符
符合以上條件方可通過。

**Comment by hoyuisun** [comment]
了解，只是這邊想問因為取得時間單位皆為到分，要怎麼驗證是否小於三秒

**Comment by taipower-dreams-tester** [comment]
您好，
由於測試程式無法紀錄變流器輸出提升的時間點，建議實際用碼表計時會比較準。
按下按鈕之後若超過10秒沒有收到電流值的deadband，測試程式也會判定為timeout。

**Comment by hoyuisun** [comment]
了解，謝謝！
