### ISSUE TITLE
第三大測項之測試

### ISSUE THREAD

**Issue by hoyuisun** [taipower-dreams-tester/dreams-cloud-joint-tester#22]
此問題與先前issue有關 #6
測試發現上列"逆變器的 PF 設定值"與"PF"這兩個數值都須透過deadband回傳
因此，這邊想確認這兩個數值都是要用deadband回傳嗎
假設若為是，逆變器的 PF 設定值這個deadband觸發的機制為何，會是同如PF(AI index:09) 1%嗎
<img width="487" alt="Screen Shot 2021-03-02 at 3 31 27 PM" src="https://user-images.githubusercontent.com/4025334/109613761-93b92180-7b6c-11eb-9b75-0cd446689775.png">

**Comment by taipower-dreams-tester** [comment]
您好，
功率因數設定值為點位14，回傳deadband條件為只要值有變動即需回傳。
![2021-03-02_18h34_54](https://user-images.githubusercontent.com/76514336/109636147-3205b100-7b86-11eb-82b9-3abd106abbc6.png)
