### ISSUE TITLE
[1-1] 請問各ID的問題

### ISSUE THREAD

**Issue by seanchang015181** [taipower-dreams-tester/dreams-cloud-joint-tester#23]
剛入門, 很多概念不是很懂, 再請協助:

1. 從Webapi可查詢到兩個電號ID分別是4 & 5
[{"plantName":"工研院測試案場","plantNo":"99-99-9999-99-9","dnp3Address":4},{"plantName":"test uncontrol plant","plantNo":"88-88-8888-88-8","dnp3Address":5}]

2. 按開始測試後推斷Dreams模擬器ID是"3", 請問這個是固定的嗎?

3. 按測試後有看到From 3 to 4與From 3 to 5封包, 但不知道受測Cloud ID為何? 我設定5結果通過了......

**Comment by taipower-dreams-tester** [comment]
您好，
是的，master的ID固定為3。
受測雲端監控系統應備有兩個案場，其一為模擬案場，需將資料收集器攜往工研院設置，並需能接收控制指令(以下簡稱可控案場)，另一則為自備案場，僅傳送資料(以下簡稱不可控案場)。
因此這兩個案場需各有一個對應的outstation，ID分別為4(可控案場)以及5(不可控案場)。

**Comment by seanchang015181** [comment]
您好,
請問意思是不是Cloud要起兩個虛擬的outstation(ID4&5), 對應模擬案場跟實際案場的outstation

**Comment by taipower-dreams-tester** [comment]
您好，
是的，您的理解沒有錯。

**Comment by jp4jp4wu6** [comment]
剛入門, 很多不很理解, 煩請協助:
目前是將Dreams安裝在本機做測試，
請問測試連線中，對接規格中有甚麼要注意的??
以下是建立連線失敗畫面

![image](https://user-images.githubusercontent.com/79955266/109781354-cd5c5c00-7c42-11eb-8dfe-1f0bfedbb699.png)

**Comment by seanchang015181** [comment]
用Chrome工具好像看不出來DNP3 Connection
建議用看封包的軟體, 比較可以看得懂資訊流

**Comment by seanchang015181** [comment]
啟2個Outstation後, 1-1, 1-2都可以通過了
