### ISSUE TITLE
找不到「以電號向DREAMS拿取案場電號ID」之API

### ISSUE THREAD

**Issue by jp4jp4wu6** [taipower-dreams-tester/dreams-cloud-joint-tester#24]
在本機模擬系統中我找不到該API的位置，以下是分別調用的URL位置
`http://localhost/api/plants/plantMeterNo/88-88-8888-88-8/token=site_token_for_cloud_jointer`

![image](https://user-images.githubusercontent.com/79955266/110054685-83848a80-7d96-11eb-83a5-3ba61251ea70.png)

也從[這裡](https://github.com/taipower-dreams-tester/dreams-cloud-joint-tester/issues/2#issuecomment-669649087)得知了另一個方法
`https://localhost/api/Gateways/getDnp3Addresses/site_token_for_cloud_jointer?access_token=site_token_for_cloud_jointer`

![image](https://user-images.githubusercontent.com/79955266/110054768-aca51b00-7d96-11eb-8bc5-270b54dc48e9.png)

localhost畫面
![image](https://user-images.githubusercontent.com/79955266/110054819-c6466280-7d96-11eb-8e75-1706ca4d9978.png)

感謝你的回覆

_Originally posted by @jp4jp4wu6 in https://github.com/taipower-dreams-tester/dreams-cloud-joint-tester/issues/2#issuecomment-791079844_

**Comment by taipower-dreams-tester** [comment]
您好，
請試試看將URL改成:
https://localhost/api/Plants/plantMeterNo/88-88-8888-88-8?access_token=site_token_for_cloud_jointer

**Comment by jp4jp4wu6** [comment]
感謝回覆。

**Comment by RareKung** [comment]
你好

以電號向DREAMS拿取案場電號ID，使用以下URL
`https://localhost/api/Plants/plantMeterNo/88-88-8888-88-8?access_token=site_token_for_cloud_jointer`
得到回饋如下附圖

![image](https://user-images.githubusercontent.com/79190847/138022166-61216f44-feb8-4941-a3f0-4692407363f0.png)

請協助
