### ISSUE TITLE
[2-1] 問題

### ISSUE THREAD

**Issue by seanchang015181** [taipower-dreams-tester/dreams-cloud-joint-tester#25]
目前在開發2-1
請問LogRegistersMeters這個api的功能是什麼?
是指回傳給DREAMS模擬器的答案嗎?

另外測試情境電號只有2個, 為什麼API查出來會是多筆?
![擷取](https://user-images.githubusercontent.com/49489353/110083230-687f3e00-7dc9-11eb-8245-cdf3262a04c1.PNG)

**Comment by taipower-dreams-tester** [comment]
您好，
LogRegistersMeter這個API主要是查詢雲端系統回傳給DREAMS測試程式的歷史資料，所以會收到這兩個情境電號在不同時間的資料。

**Comment by seanchang015181** [comment]
剛剛發現好像有時候可以, 有時候會timeout, 還在研究怎麼複製異常情境

請問出現下面畫面, 到時候認證比對現場資訊, 是不是就可以通過了?
![擷取1](https://user-images.githubusercontent.com/49489353/110302078-cf079480-8033-11eb-9d26-896e427a45e6.PNG)
![擷取2](https://user-images.githubusercontent.com/49489353/110302105-d75fcf80-8033-11eb-889f-8d579a76cbf0.PNG)

**Comment by taipower-dreams-tester** [comment]
您好，
是的，只要有正常收到資料，並且數值與現場裝置資訊符合即可。

**Comment by seanchang015181** [comment]
感謝~
