### ISSUE TITLE
1-1, 1-2的問題

### ISSUE THREAD

**Issue by jp4jp4wu6** [taipower-dreams-tester/dreams-cloud-joint-tester#26]
啟2個Outstation後, 1-1, 1-2都可以通過了

_Originally posted by @seanchang015181 in https://github.com/taipower-dreams-tester/dreams-cloud-joint-tester/issues/23#issuecomment-791169898_

請問，1-1DREAMS要連上受測雲端資料系統是否有需要增加其他DREAMS辨識條件? 還是IP&port正確就可以連上??
另外受測Cloud ID是如何設置??

感謝你的回覆。

**Comment by taipower-dreams-tester** [comment]
您好，
由於實際上DREAMS系統與雲端資料系統會走MDVPN並以VPN內部IP連接，因此目前並沒有規劃額外的辨識條件。
Cloud ID的部分，請依照規範上以API方式取得電號與ID的對照表。

**Comment by jp4jp4wu6** [comment]
遇到跟[這裡](https://github.com/taipower-dreams-tester/dreams-cloud-joint-tester/issues/15#issue-812528307)一樣的問題
```
此項Dreams平台怎麼驗證成功連線受測資料系統
telnet受測資料系統的port是有通的，但Dreams模擬伺服器皆顯示不通過
```
本機mater測試port有通，但DREAMS 1-1測試皆顯示不通過。

另外以API方式取得電號與ID的對照表後，要如何在outstation設置ID??

感謝你的回覆。

**Comment by seanchang015181** [comment]
主程式起2個Outstation就可以了 (Local ID開發先寫死, 之後要用API取得)
1. Loacl=5, Remote=3
2. Local=4, Remote=3

**Comment by jp4jp4wu6** [comment]
> 主程式起2個Outstation就可以了 (Local ID開發先寫死, 之後要用API取得)
> 
> 1. Loacl=5, Remote=3
> 2. Local=4, Remote=3

非常感謝回覆。

在我填入IP & port送出之前是無法從API取得電號的，無法先取得Cloud ID是正常嗎??
DREAMS連線時只設定一組IP&port，如主程式設置兩組outstations應會用到兩組port，
Dreams與兩組outstation之間關係我就不是很能理解了。

剛入門，很多概念不是很懂，還請協助，
再次感謝兩位撥空回覆。

**Comment by taipower-dreams-tester** [comment]
您好，
>在我填入IP & port送出之前是無法從API取得電號的，無法先取得Cloud ID是正常嗎??
是的，目前設計是如此。填入IP & port之後才會將對應電站資訊建立出來。

> DREAMS連線時只設定一組IP&port，如主程式設置兩組outstations應會用到兩組port
雖然有兩個outstation但應該只要建一個channel，因此應該只需要一組port喔
上述有提到兩個outstation的remote ID都是3，這是因為DREAMS端的master只有一個，而且它的ID是3。

**Comment by jp4jp4wu6** [comment]
從 https://github.com/taipower-dreams-tester/dreams-cloud-joint-tester/issues/15#issuecomment-797326580 了解到 DREAMS 第一項的主要測試內容為 DREAMS mySQL 中有無雲端測試資料。

![image](https://user-images.githubusercontent.com/79955266/111099193-f30d2d80-857f-11eb-97de-18aa8e974abc.png)

這邊觀察 openDNP3 master 跟 outstation 啟動時，master 會走 TCP 與 outstation 的 20000port 溝通再開始走 DNP3，
然而填入 IP & port，DREAMS 建立基本資料中，卻沒發現有任何與 20000port 溝通的痕跡。

不知道從這方向去了解是否正確。

非常期待並在此先感謝你的回覆。

**Comment by taipower-dreams-tester** [comment]
您好，
填入IP & port之後測試程式就會依照您填的資訊建立對應的outstation，並且讓master重啟以套用新的設定。這時候master應該就會透過20000 port跟outstation建立連線(除非您填的port不是20000)。

**Comment by jp4jp4wu6** [comment]
> 您好，
> 填入IP & port之後測試程式就會依照您填的資訊建立對應的outstation，並且讓master重啟以套用新的設定。這時候master應該就會透過20000 port跟outstation建立連線(除非您填的port不是20000)。

你好，
原本是這樣的思維，因DREAMS與openDNP3預設是20000port，
沒做更改的情況下，DREAMS應該會嘗試與20000port的outstation做連線，
但納悶的是不見DREAMS有做溝通的跡象，而用其他軟體測試20000port，outstation皆有反應。
以上皆在本機做測試，目前還在找解決辦法。

所以才請教大家有什麼建議方法或有什麼要注意的地方。

**Comment by hoyuisun** [comment]
你outstation有幾個?!，看你封包有回應才對@@

**Comment by jp4jp4wu6** [comment]
> 你outstation有幾個?!，看你封包有回應才對@@

目前 openDNP3 內有一個 outstation，
可能沒說明清楚，那截圖是 openDNP3 的 master 與 outstation 溝通狀況，
我是從這發現 master 會走 TCP 與 outstation 的 20000port 溝通再開始走 DNP3，
用wireshark觀察 DREAMS 與 outstation 間狀況，從點擊"開始測試"按鈕前到顯示"測試畫面"為止，
發現沒有同樣的情形產生，目前大概是這樣。

不知道有什麼建議方法或是哪裡需要注意。

**Comment by jp4jp4wu6** [comment]
![image](https://user-images.githubusercontent.com/79955266/111270933-75265080-866b-11eb-8c2b-3417aa0a77fc.png)

發現每次重啟後點擊測試按鈕後，都會有訪問5037port的狀況，因為該port沒有占用，嘗試把outstation改為5037port，就有反應了，這樣表示DREAMS在建立資料時，並沒有對20000port發出請求呀??

**Comment by seanchang015181** [comment]
Protocol要過濾只看DNP3, TCP不需要看
連線是在一開始"開始測試"那個按鈕
1-1, 1-2的按鈕並不會有連線

**Comment by jp4jp4wu6** [comment]
> Protocol要過濾只看DNP3, TCP不需要看
> 連線是在一開始"開始測試"那個按鈕
> 1-1, 1-2的按鈕並不會有連線

對的，就是在"開始測試"那個按鈕點擊後，發現沒有對20000port發出請求，無DNP3傳輸，
也理解1-1、1-2是對table內的資料做比對。
各位可以測試通過表示DREAMS應該是有發出請求以及將outstation回應內容寫入table，才能應對接下來的測試。
有把outstation及DREAMS測試網頁中輸入port改為其他，但發現都沒有反應，目前找不到原因。

**Comment by seanchang015181** [comment]
可能把DNP3所有log貼出來才看得出來原因
TCP不需要看

你要看到From 4 to 3還有From 5 to 3才會成功
![image](https://user-images.githubusercontent.com/49489353/111289308-fee01900-867f-11eb-873e-c9e89d9654d0.png)

**Comment by jp4jp4wu6** [comment]
> 你要看到From 4 to 3還有From 5 to 3才會成功

非常感謝協助解答，目前尚未有側錄到dnp3傳輸，
看起來是dnp3Address要設置才會成功，
但不懂該如何在outstation code中設置dnp3Address，
還須請教seanchang015181。

**Comment by seanchang015181** [comment]
官網Sample Code看懂1-1, 1-2應該就可以通過了
https://dnp3.github.io/#documentation

後面會難在光靠OpenDNP3無法滿足認證情境需求, 需要自己改寫OpenDNP3

**Comment by jp4jp4wu6** [comment]
> 官網Sample Code看懂1-1, 1-2應該就可以通過了
> https://dnp3.github.io/#documentation

感謝seanchang015181的提醒，

DREAMS操作說明的第二步驟
`2.請輸入待測雲端系統之IP位址等必要資訊。同時API Token也請代入雲端系統，方能取得電號與DNP 3.0 address的對照表
`
請問API Token是如何帶入雲端系統??dnp3有這項機制嗎???

**Comment by taipower-dreams-tester** [comment]
您好，
DNP3沒有這項機制。
前面提到的dnp3Address雖然過認證時目前為4跟5，但實際上接入DREAMS時dnp3Address需透過RESTful API取得。
請參考 [再生能源監控設備雲端資料系統試驗及管理規範](https://www.taipower.com.tw/upload/123/2021011514315169391.pdf) 第10頁，同時在呼叫API時將token帶入，方能取得電號與dnp3Address的對照表。

**Comment by jp4jp4wu6** [comment]
> 前面提到的dnp3Address雖然過認證時目前為4跟5，但實際上接入DREAMS時dnp3Address需透過RESTful API取得。

了解，原來是指這個部分。
溝通流程：
點擊開始測試 -> DREAMS建立對應電站資訊 -> outstation透過RESTful API取得電站資訊 -> outstation傳回電站資訊 -> DREAMS將電站資訊寫入mySQL -> 進入測試畫面。

這樣理解是對的嗎???

開兩個outstation 分別先寫死Local=4跟5，Remote=3
DREAMS IP&port 輸入正確，應該也可以對接上吧??

**Comment by taipower-dreams-tester** [comment]
您好，
您的理解沒有錯。
另外目前outstation雖然可以先寫死4跟5，但為確保通過測試的廠商具備日後正常接入DREAMS系統的能力，工研院仍然保有隨時更改的權力。建議還是確實實作以API拿dnp3Address的功能喔。

**Comment by jp4jp4wu6** [comment]
> 溝通流程：
點擊開始測試 -> DREAMS建立對應電站資訊 -> outstation透過RESTful API取得電站資訊 -> outstation傳回電站資訊 -> DREAMS將電站資訊寫入mySQL -> 進入測試畫面。

請問其中 `outstation傳回電站資訊` 這部分是走RESTful API還是DNP3呢??

**Comment by taipower-dreams-tester** [comment]
您好，
是走DNP3喔，RESTful API僅有取得電號與dnp3Address對照表的功能。

**Comment by jp4jp4wu6** [comment]
> 溝通流程：
點擊開始測試 -> DREAMS建立對應電站資訊 -> outstation透過RESTful API取得電站資訊 -> outstation傳回電站資訊 -> DREAMS將電站資訊寫入mySQL -> 進入測試畫面。

這樣看來，一開始DREAMS DNP3master並不會先主動發出polling，而是由outstation先透過RESTful API取得電站資訊，且主動透過DNP3傳電站資訊後，當DREAMS DNP3master收到正確資訊後，才會開始主動polling。

這樣理解是對的嗎???

**Comment by taipower-dreams-tester** [comment]
您好，
看來我有點誤會您的意思，實際溝通流程如下：
1. 點擊開始測試
2. DREAMS將對應電站資訊寫入MySQL並重啟dnp3 master。dnp3 master重啟後便會依照所輸入的IP/port，嘗試與雲端受測平台建立DNP3連線(**dnp3 master重啟完成後便會進入測試畫面**)。
3. 於此同時雲端受測平台應透過RESTful API取得電站資訊，並建立對應outstation(local dnp3 address為4 and 5)，方能接收由master來的連線請求。
4. master/outstation兩端都準備好後連線便會建立。依照規範master會進行一次polling(後續除非master有重啟(測項4-1)或台電有手動polling需求(測項2-1)，否則將不會再有polling)，之後outstation必須自主於每15分鐘以及有deadband時回傳發電資料。

**Comment by jp4jp4wu6** [comment]
> 2. DREAMS將對應電站資訊寫入MySQL並重啟dnp3 master。dnp3 master重啟後便會依照所輸入的IP/port，嘗試與雲端受測平台建立DNP3連線(dnp3 master重啟完成後便會進入測試畫面)。
> 3. 於此同時雲端受測平台應透過RESTful API取得電站資訊，並建立對應outstation(local dnp3 address為4 and 5)，方能接收由master來的連線請求。

依照上述兩點，流程上的順序在此釐清一下
-> DREAMS將對應電站資訊寫入MySQL並重啟dnp3 master
-> 雲端受測平台應透過RESTful API取得電站資訊，並建立對應outstation localAddr及remoteAddr
-> dnp3 master完成後便會進入測試畫面，且會依照所輸入的IP/port嘗試與之建立DNP3連線

1. dnp3 master重啟並不影響透過RESTful API取得電站資訊
2. 進入測試畫面後"才"依照所輸入的IP/port建立DNP3連線

這樣流程理解對嗎???

> 4. master/outstation兩端都準備好後連線便會建立。依照規範master會進行一次polling(後續除非master有重啟(測項4-1)或台電有手動polling需求(測項2-1)，否則將不會再有polling)，之後outstation必須自主於每15分鐘以及有deadband時回傳發電資料。

再請問
第四點"依照規範master會進行一次polling"
與
第二點"便會依照所輸入的IP/port，嘗試與雲端受測平台建立DNP3連線"
是同一個步驟嗎???

**Comment by taipower-dreams-tester** [comment]
@jp4jp4wu6 您好,

> 1. dnp3 master重啟並不影響透過RESTful API取得電站資訊
> 2. 進入測試畫面後"才"依照所輸入的IP/port建立DNP3連線
> 這樣流程理解對嗎???

1. 不會
2. 不是的，要等到DNP3連線建立完之後才會進入測試畫面

> 再請問
> 第二點依照所輸入的IP/port，嘗試與雲端受測平台建立DNP3連線
> 第四點依照規範master會進行一次polling
> 是指同一個動作嗎???

第四點說的連線建立跟第二點說的連線建立是同一件事情，建立完之後masetr會立刻進行polling
