### ISSUE TITLE
按下開始測試 controlDnp3Master 無回應

### ISSUE THREAD

**Issue by sunwareIzumi** [taipower-dreams-tester/dreams-cloud-joint-tester#29]
如題 按下開始測試後 
https://localhost/api/Controls/controlDnp3Master?access_token=top_secret
沒有回應 有確認 收到 dnp3 的封包 也有回應

**Comment by taipower-dreams-tester** [comment]
您好，
建議您可以從[這裡](https://github.com/taipower-dreams-tester/dreams-cloud-joint-tester/blob/4b1a7f37597c4aa383fc4176dcbb299e694de748/rest/rest-api-dreams/common/models/control.js#L14)下中斷點以確認API無回應的原因。
controlDnp3Master主要是用於啟動/停止或是重啟dnp3 master的docker instance，以套用您的outstation設定。

**Comment by taipower-dreams-tester** [comment]
您好，
方便將加了LOG的原始碼貼上來嗎? 單純從LOG難以判斷是發生什麼事了。

**Comment by sunwareIzumi** [comment]
> 您好，
> 方便將加了LOG的原始碼貼上來嗎? 單純從LOG難以判斷是發生什麼事了。

'use strict';

const debug = require('debug')('application:control');
var docker = require('../utils/docker');

module.exports = function(Control) {
  Control.remoteMethod('controlDnp3Master', {
    http: {path: '/controlDnp3Master', verb: 'post'},
    accepts: [
      {arg: 'operation', type: 'string', required: true, description: 'start | stop | restart'},
    ],
    returns: {arg: 'data', type: 'object'},
  });

  Control.controlDnp3Master = async function(operation) {
    const dnp3Master = await docker.getService('dnp3-master');
debug('izumi debug :: dnp3Master is undefined %s', (typeof dnp3Master == 'undefined' ? 'Yes.' : 'No.'));
console.log('izumi debug :: dnp3Master is undefined ' + (typeof dnp3Master == 'undefined' ? 'Yes.' : 'No.'));
    if (operation === 'start') {
      await dnp3Master.start();
      return { output: 'success' };
    } else if (operation === 'stop') {
      await dnp3Master.stop();
      return { output: 'success' };
    } else if (operation === 'restart') {
debug('izumi debug :: dnp3Master before restart %s', Date.now());
console.log('izumi debug :: dnp3Master before restart ' + Date.now());
      await dnp3Master.restart();
debug('izumi debug :: dnp3Master after restart %s', Date.now());
console.log('izumi debug :: dnp3Master after restart ' + Date.now());
      return { output: 'success' };
    }
  }
};

已附上

**Comment by taipower-dreams-tester** [comment]
看起來應該是有成功結束，方便附一下Chrome的DevTools畫面嗎?
例如:
![2021-03-17_16h08_02](https://user-images.githubusercontent.com/76514336/111434861-06b0c380-873b-11eb-8d15-7afe92f18cf9.png)

**Comment by sunwareIzumi** [comment]
![image](https://user-images.githubusercontent.com/79885194/111436601-1f21dd80-873d-11eb-896e-039d4ca5c3d8.png)

**Comment by sunwareIzumi** [comment]
我想問一下
為什麼你用 3000 PORT 去RUN 

我如果 改用 3000 PORT 系統會直接無回應 必須使用 443 PORT

但 dnp3-master main.cpp 中，去取得 api/Plant 資料 卻強制寫死 3000 PORT
測試程式必須 走 443 PORT 測試嗎??

**Comment by taipower-dreams-tester** [comment]
您好，
3000 port是用debug mode單跑API server而不經過nginx的情況，loopback預設的port是3000。
但測試程式整套跑起來的時候，nginx裡面的設定有將loopback的3000 port redirect到443 port，因此測試程式的網頁是以443連接API server。而dnp3-master因為是local docker之間互通，因此走3000 port即可。

另外想問一下您切到timing頁面後是否看到他是Stalled呢? 如果是，DURATION顯示的是多久呢?
![2021-03-17_17h23_05](https://user-images.githubusercontent.com/76514336/111444933-d91d4780-8745-11eb-94dc-0cf1041f809d.png)

**Comment by sunwareIzumi** [comment]
![image](https://user-images.githubusercontent.com/79885194/111445545-77a9a880-8746-11eb-8550-46877cdb8a4e.png)


這個 我測試發現 WEB 有收到回應 然後就會拋出 Network Error 的錯誤 
因為 dnp3-master restart 大概 10秒

**Comment by taipower-dreams-tester** [comment]
您好，
我的環境(WIN10)要超過2分鐘才會進入Stalled的狀態，之前在Ubuntu上測試時也沒有遇過這樣的問題，猜測是Chrome版本或設定的問題。如果您從別台機器連測試網頁也會有一樣的問題嗎?

**Comment by sunwareIzumi** [comment]
用別台連可以 本機使用 FIREFOX 也可以 有點奇怪的問題

感謝你的協助
