### ISSUE TITLE
dreams-tester.plato-io.com 的 99-99-9999-99-9 案場電號已經存在

### ISSUE THREAD

**Issue by coolwang2** [taipower-dreams-tester/dreams-cloud-joint-tester#3]
您好：

我們連線至工研院的測試程式，出現這樣的結果，該怎麼辦呢？
1. 是請您們將 dream server 重啟嗎？
2. 關閉 dream server 上的測試程式網頁？

麻煩您們了, 
謝謝

![image](https://user-images.githubusercontent.com/16569335/99637475-deac9e80-2a7f-11eb-8682-e1096ca12d72.png)

**Comment by kyatapi** [comment]
您好，由於本程式設計上，同時僅能有一個人進行測試，因此出現該訊息代表已經有其他人在進行使用喔。
基本上給工研院用的網址，政策上是不對外開放的。如果是開發中要測試，還請您自行架設測試用server喔。
程式碼或架設步驟如果有不清楚的地方，歡迎在此提問。

**Comment by derting** [comment]
Duplicate of #1 

解決方式：
一、進到mySQL中，把dreams_business's Plant表的資料清空即可恢復正常。
二、砍掉所有相關 Containers，重新Run一次deploy.sh亦可正常。

**Comment by coolwang2** [comment]
明白，
感謝 derting, kyatapi 撥空回覆！

**Comment by taipower-dreams-tester** [comment]
@coolwang2 如果問題已經解決，還煩請將本Issue關閉喔。
感謝幫忙!
