### ISSUE TITLE
DNP3 Slave 測試程式

### ISSUE THREAD

**Issue by sunwareIzumi** [taipower-dreams-tester/dreams-cloud-joint-tester#30]
想請問一下 這個專案能使用 DNP3 Slave 測試程式嗎
試過 德國套裝的無法測試 有建議的測試程式可以測試嗎

**Comment by taipower-dreams-tester** [comment]
您好，
沒有特別試過其他套裝DNP3 slave程式，不過dnp3 masetr是基於opendnp3開發的，如果設定沒有錯，理論上單純建立連線應該沒有問題。不過每15分鐘定期unsolicited回傳的部分就不確定一般套裝軟體是否能夠滿足了。

**Comment by sunwareIzumi** [comment]
好的 了解了 謝謝
