### ISSUE TITLE
請問點位33 - 案場電號資料格式

### ISSUE THREAD

**Issue by seanchang015181** [taipower-dreams-tester/dreams-cloud-joint-tester#33]
請問這個點位資料是填以下哪一個格式?
1. 99-99-9999-99-9
2. 99999999999
3. 4

**Comment by taipower-dreams-tester** [comment]
您好，
請參考最新[點位規範](https://www.taipower.com.tw/upload/123/2021032914494851900.pdf)，已無需回傳點位33。
