### ISSUE TITLE
4-1 三筆資料的問題

### ISSUE THREAD

**Issue by seanchang015181** [taipower-dreams-tester/dreams-cloud-joint-tester#35]
您好,
我在測4-1情境的時候, 雖然有顯示Pass, 但資料顯示怪怪的, 請協助

測試期間Cloud總共傳了4筆資料給DREAMS
9:00 URBE斷線重傳
9:15 URBE斷線重傳　
9:15 應該是DREAMS Polling
9:30 URBE定時主動傳送 ==> 這筆傳送後測驗結果才出現

但是畫面結果只顯示後面三筆(9:15, 9:15, 9:30), 
9:00那筆沒有顯示

請問這樣算通過嗎?

![image](https://user-images.githubusercontent.com/49489353/114800992-6bf4e480-9dcd-11eb-8185-e9e3e3210969.png)

**Comment by taipower-dreams-tester** [comment]
您好，
測試程式會再收到3筆完整資料後才顯示結果，推測應該是9:00的那筆資料並沒有成功傳給測試程式。
建議若您有自架設測試程式，可以在MySQL裡面確認一下是否資料真的有收到。

**Comment by seanchang015181** [comment]
您好,
我看MySQL後發現DREAMS重啟後是否只有對ID-4 Polling, 
ID-5我看資料庫少一筆資料, 難怪要等到下一個15分主動回報才會結束

![image](https://user-images.githubusercontent.com/49489353/115530448-5c423800-a2c6-11eb-8d51-dc535944a1ed.png)

**Comment by seanchang015181** [comment]
您好,
我把4-1流程整理成下圖, 請問理解是否正確
1. 我查詢MySQL, 11:00 Polling未成功拋給DREAMS, 是否11:20重啟時
2. 11:20 DREAMS是否只對outstation "4" polling ? 5是否沒有polling ?

![image](https://user-images.githubusercontent.com/49489353/115803021-93bdfb00-a412-11eb-882c-827519e36cc0.png)

**Comment by seanchang015181** [comment]
感謝, 我好像試成功了, 這是我的測試畫面, 這項應該就可以通過吧

![image](https://user-images.githubusercontent.com/49489353/116170506-8918a400-a739-11eb-8d24-cdfed14f495e.png)
