### ISSUE TITLE
Installation  Error

### ISSUE THREAD

**Issue by Anish009** [taipower-dreams-tester/dreams-cloud-joint-tester#42]
Dear Sir,

Today, I was trying to install the dream-server and got this error 
<img width="442" alt="dream1" src="https://user-images.githubusercontent.com/32253394/124530495-3517f300-de3f-11eb-86bb-5240a9713708.PNG">
Can you please do the needful thing to solve the issue?

Thank you in advance, for your support.

**Comment by derting** [comment]
Update the file `dreams-cloud-joint-tester/tester-web/Dockerfile`
Line1 => `FROM node:10.14.2`
10.14.2 is too old. You need the node.js lastest version. (In my case is 14.18.0, see https://nodejs.org/en/)

**Comment by derting** [comment]
這邊也遇到相同的問題，有嘗試將Dockerfile node.js 版本改成12以上可以避開[2/4], 但[4/4]時仍然會有問題。
煩請協助處理。

**Comment by taipower-dreams-tester** [comment]
Dear Sir,

This issue should be solved by updating node version as well as the sharp (node module) version. This is now included in the latest version, please kindly give it a try. Many thanks.

**Comment by Anish009** [comment]
ok thank you

**Comment by RareKung** [comment]
https://github.com/taipower-dreams-tester/dreams-cloud-joint-tester/issues/42#issuecomment-943073869 已解決版本變更問題。
從tester-web底下Dockerfile內容作更動。

但[4/5]還是會有錯誤發生。
![image](https://user-images.githubusercontent.com/79190847/137275662-73a41aa0-5ffe-4512-ba92-aeb177fed318.png)

**Comment by taipower-dreams-tester** [comment]
@RareKung 您好,

如果ENOSPC是您看到的唯一錯誤，那要請您確認一下磁碟空間是否足夠囉

**Comment by RareKung** [comment]
@taipower-dreams-tester 感謝你的回覆。
