### ISSUE TITLE
以電號向DREAMS拿取案場電號ID

### ISSUE THREAD

**Issue by RareKung** [taipower-dreams-tester/dreams-cloud-joint-tester#44]
你好

以電號向DREAMS拿取案場電號ID，使用以下URL
`https://localhost/api/Plants/plantMeterNo/88-88-8888-88-8?access_token=site_token_for_cloud_jointer`
得到回饋如下附圖

![image](https://user-images.githubusercontent.com/79190847/138796024-49e1701d-56cc-40fc-8377-5293d3becea9.png)

煩請協助

**Comment by taipower-dreams-tester** [comment]
已在[#24](https://github.com/taipower-dreams-tester/dreams-cloud-joint-tester/issues/24)回覆，故關閉Issue
