### ISSUE TITLE
4-1 回傳資料無法正確顯示

### ISSUE THREAD

**Issue by HJL0523** [taipower-dreams-tester/dreams-cloud-joint-tester#45]
您好：

附圖為我方測試畫面：
![4-1 - Timeout 1420](https://user-images.githubusercontent.com/91720016/139644132-ddc895d4-1bd7-44c9-ab27-855fed40272a.png)

我們在dreams tester回復連線之後利用wireshark 的確觀察到outstation 回傳class 1x2 和 class 0x1 的資料，但是tester似乎沒有顯示。
![4_1_2](https://user-images.githubusercontent.com/91720016/139644244-6a4dc987-b66d-40f1-83db-30b913cdb880.png)

此外，當我們強制寫入兩次class 1資料後，該測試會通過，但是顯示之資訊為：
1. Class 0: 重新連線之後的polling資料。
2. Class 1: 強制寫入的兩項資料，並非斷線期間所儲存之資料。

在此附上wireshark log，欲請教請問是傳輸資料有問題嗎，還是此測試除了偵測class 1x2 和 class 0x1 之外還有其他的偵測標準？

謝謝您的解答。
[Wireshark_DREAMS_2021_11_01_Driver_4_0_42D_Test_4_1_Only_and_Static_Data_Failed_with_TimeOut_2.zip](https://github.com/taipower-dreams-tester/dreams-cloud-joint-tester/files/7451803/Wireshark_DREAMS_2021_11_01_Driver_4_0_42D_Test_4_1_Only_and_Static_Data_Failed_with_TimeOut_2.zip)

**Comment by taipower-dreams-tester** [comment]
您好,
請檢查針對兩個案場總共6筆資料，是否都有完整回傳全部33個點位。

**Comment by HJL0523** [comment]
您好：
根據台電DREAMS規範，我們只需要回傳32筆AI，請問第33筆資料為哪一筆資料? 如果是按照32筆資料來看，我方回傳32*2=64是沒問題的。此外，關於DREAMS DNP3 master，如果我回傳64筆class 1資料，請問它有辦法可以分辨出是兩筆class 1各32點還是1筆class 1 有64點?
![image](https://user-images.githubusercontent.com/91720016/142095242-30d6a4ed-a44c-4a2d-afd9-1eea1b8e3191.png)
最新規範：https://www.taipower.com.tw/upload/123/2021070718370591246.pdf

**Comment by taipower-dreams-tester** [comment]
您好，
了解，舊的規範有多了點位31: 累積發電量deadband設定值，這邊我們程式會再做修正。
另外您的一筆class 1有64點指的是都用同一個SEQ(sequence number)嗎? 如果這樣是無法辨識的，請拆成兩筆。

**Comment by HJL0523** [comment]
您好：

謝謝您的回答。
關於32點位的部分，沒問題。
關於同一個SEQ部分，我們需要近一步的說明：

1. 當dreams - outstation 回連時，dreams 會disable spontaneous message (outstation無法自行回傳unsolicited)而DREAMS會根據response裡面的IIN bit: class1 data available 來傳送 Read 1230。
2. 收到 Read1230指示，outstation 回傳 class 1 data (64 筆) -> class 2 data (4-1這裡沒有模擬) -> class 3 data (規範無定義) -> class 0 data (static)，之後reset IIN bit: class 1 available -> 0, 所以DREAMS不會再傳送Read 1230
3. 資料收到後，DREAMS enable spontaneous message，完成回連程序。

我們的問題是，如果要把所有資料都一起回傳的話，class1 資料要如何分成不同SEQ? 請問開發團隊是否有開發時的模擬測試的wireshark log讓我們看一下實際上長得如何? 我方測試時只能取得以下結果:
![image](https://user-images.githubusercontent.com/91720016/142120478-bcfff9b8-0a39-4928-8f0c-f1a48ee18c84.png)

我們是否能把 64 points 改成：
Object(s) : 32-bit Analog Change Event with Time (Obj:32, var:03) (0x2003), 32 points
Object(s) : 32-bit Analog Change Event with Time (Obj:32, var:03) (0x2003), 32 points
Object(s) : 32-bit Analog Input (Obj:30, var:01) (0x1e01), 32 points

而不是
Object(s) : 32-bit Analog Change Event with Time (Obj:32, var:03) (0x2003), 64 points
Object(s) : 32-bit Analog Input (Obj:30, var:01) (0x1e01), 32 points

**Comment by taipower-dreams-tester** [comment]
您好，
DREAMS在master剛啟動的時候的確會disable spontaneous message，並做一次all class scan，這次scan您應該回傳當下可以取得的最新資料。而4-1要驗證的兩筆斷線期間定時資料應該在這之後再由Unsolicited的方式回傳。

舉例來說11:20您按下4-1開始測試，理論上會在11:51結束測試。
若11:51有取得最新資料，則單一案場而言回傳的三筆資料按照收到的順序應該依序是：
1. 11:51 (scan)
2. 11:30 (unsolicited)
3. 11:45 (unsolicited)

**Comment by HJL0523** [comment]
您好：
照您的意思，all class scan 的時候我們不能回傳class 1的資料。要等到enable spontaneous message之後才可回傳嗎?
照您的意思的話，當我們有 (disable spontaneous message) 和 (read 1230) 這兩者同時存在的時候我們面對read 1230 request 不能回傳class 1 嗎?
是否能有wireshark 封包log可以給做參考? 我們的開發團隊在國外所以用這種方式比較好溝通。

謝謝您的回答

**Comment by taipower-dreams-tester** [comment]
您好，
all class scan的時候還是要回傳class 1的資料，但他應該只有32個點位，並且這32個點位的值應該是您當下可以取得的最新資料。
這裡僅就規範討論，目前恕無法提供wireshark log。
如果您有需求我們也可以用英文溝通。

**Comment by HJL0523** [comment]
您好，

根據規範，class 1只有在每十五分鐘才會回傳，您的意思是說當all class scan 的時候也要回傳當下scan時間的class 1資料嗎?
以您的例子來說：

11:20我按下4-1開始測試，理論上會在11:51結束測試。
若11:51有取得最新資料，則單一案場而言回傳的三筆資料按照收到的順序應該依序是：

1.  11:51 (scan - class 1)
2.  11:51 (scan - class 0)
3.  11:30 (unsolicited - class 1)
4.  11:45 (unsolicited - class 1)

而根據 source code，當item >= 3, 會取最先三筆資料，所以我們會拿到:
1.  11:51 (scan - class 1)
2.  11:51 (scan - class 0)
3.  11:30 (unsolicited - class 1)

這樣的話結果是不正確的，可以請您針對「all class scan的時候還是要回傳class 1的資料，但他應該只有32個點位，並且這32個點位的值應該是您當下可以取得的最新資料。」再解釋一次嗎?

**Comment by taipower-dreams-tester** [comment]
您好，
測試程式在取得資料時會依時間戳排序(而非依收到順序)，再取"最先"三筆。
因此不論11:51送了幾筆，結果拿到的都會是11:30, 11:45跟11:51三筆喔。

**Comment by HJL0523** [comment]
您好：

謝謝您的答覆，我和開發組再溝通一下。如果還有問題，到時候再向您請教。

**Comment by taipower-dreams-tester** [comment]
您好，
已經將 點位31: 累積發電量deadband設定值 從測試程式中移除，有空再幫我們驗證一下喔。
感謝!

**Comment by HJL0523** [comment]
您好：

謝謝您的幫忙。關於4-1部分的問題，我們已經能讓Master 讀到想要的資料了。但是如圖所示，顯示的時間戳還是不正確 (Wireshark 裡面確認了顯示的資料的timestamp 是沒有錯誤的，但是不知道為什麼測試畫面還是顯示恢復連線當下的時間)

![image](https://user-images.githubusercontent.com/91720016/144038648-08fdae11-d52f-41bf-b9b9-d0e2b8964290.png)

我想請教上圖測試程式的「時間戳」是以什麼為基準？ 他讀的是AI的第32點的時間戳嗎？ 如果是這樣那麼時間應該是整點15分才對。
![image](https://user-images.githubusercontent.com/91720016/144039356-6d7381a6-f26f-4076-b540-bbda9249dd57.png)

謝謝您的回答。

**Comment by taipower-dreams-tester** [comment]
您好，
如果有點位32他會以點位32的時間戳為優先，否則會用master收到資料的時間。
如果您確認點位32的時間戳傳的值是正確的，那可能要看一下是否同一個時間戳的所有點位，傳送時帶的SEQ是一樣的。
