### ISSUE TITLE
以電號向DREAMS拿取案場ID

### ISSUE THREAD

**Issue by allen10153** [taipower-dreams-tester/dreams-cloud-joint-tester#47]
您好，

請問範例中為什麼丟給DREAMS的API 電號: 88-88-8888-88-8 會回傳 2組電號?

![1639019068212](https://user-images.githubusercontent.com/96039311/145760853-c9afc583-7db7-4197-9f4e-4d4214890b88.jpg)

謝謝您！

**Comment by taipower-dreams-tester** [comment]
您好，
目前此API的設計是以一個代表電號(ex: 88-88-8888-88-8)取得該雲端對接業者底下所有的電號-DNP3 address的對照表。
