### ISSUE TITLE
關於AI Table 18,19點位

### ISSUE THREAD

**Issue by RareKung** [taipower-dreams-tester/dreams-cloud-joint-tester#48]
關於點位18: 1-25變流器是否成功接受控制、點位19: 26-50變流器是否成功接受控制，
想請教:
1. 其中1-25及26-50分別代表意義為何??
2. 對於文件中附註提到「使用第1-25bit表示」不甚理解，請問當成功接受控制（附註中 成功:1）時，我們回應的內容應該長怎麼樣呢??

謝謝你的回覆

**Comment by taipower-dreams-tester** [comment]
您好，

1-25代表第1~第25台逆變器的控制成功與否，分別以這個欄位的第1~25個bit代表。也就是說假設第三台逆變器成功但其他失敗的情況，此欄位的值以10進位表示應該為4 (若以2進位表示則為100)。
26-50則以此類推，為第26~第50台逆變器的控制結果。

**Comment by RareKung** [comment]
`... 此欄位的值以10進位表示應該為4 (若以2進位表示則為100) ...`
如上，表示此點位是使用10進制及2進制擇任一回應??還是只能其一呢??

謝謝你的回覆

**Comment by RareKung** [comment]
再請教

案場變流器數量不足25時，需要補足25bit嗎??如果需要，是以0來補足嗎??
