### ISSUE TITLE
API Token 沒有值

### ISSUE THREAD

**Issue by derting** [taipower-dreams-tester/dreams-cloud-joint-tester#5]
請問 API Token 之前的版本會自動帶出，但我拉最新版本後該選單卻一直沒有值，請問該怎麼辦？
確定當前.env/rest.env已經照著說明文件操作了才對。

如下圖：
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/5178511/102186673-eb40dd00-3eed-11eb-8ab6-0b633d48484c.png">

<img width="733" alt="image" src="https://user-images.githubusercontent.com/5178511/102186859-3529c300-3eee-11eb-9c50-26773be050f1.png">

**Comment by kyatapi** [comment]
您好，請問瀏覽器的偵錯視窗有看到任何錯誤嗎?
Firefox可以按Ctrl + Shift + Z叫出偵錯視窗，方便貼一下Network分頁的截圖嗎?

**Comment by OowhitecatoO** [comment]
全新安裝的機器上
我也遇到相同問題
![image](https://user-images.githubusercontent.com/16508330/102643216-e43df700-4199-11eb-99f1-3ab3754b0afb.png)


按下開始測試後畫面卡在這邊
![image](https://user-images.githubusercontent.com/16508330/102642888-56faa280-4199-11eb-920c-a5a886c0c86f.png)

console 顯示錯誤如下
![image](https://user-images.githubusercontent.com/16508330/102642984-80b3c980-4199-11eb-9d04-65fd6484d81b.png)

**Comment by taipower-dreams-tester** [comment]
您好，已經修正CORS的問題，請下載新版程式碼再試試看。
(rest.env的內容請記得更新)

**Comment by OowhitecatoO** [comment]
您好，下載後按照說明重新安裝
問題沒有獲得改善
![image](https://user-images.githubusercontent.com/16508330/103066424-d6520100-45f3-11eb-9233-7b638c9c578c.png)

![image](https://user-images.githubusercontent.com/16508330/103066497-03061880-45f4-11eb-9209-7b2dc8318465.png)

**Comment by taipower-dreams-tester** [comment]
您好，依照偵錯視窗訊息，研判應該為後端API server執行時發生錯誤。
由於在我們的測試環境沒有發生該狀況，要請您幫忙收集一下log喔。
在您的Ubuntu機器上從console(terminal)視窗鍵入以下指令，應可收集到API server的log:

`sudo docker logs dreamscloudjointtester_master_1 > log.txt 2>&1`

log會寫入執行目錄的log.txt檔案中，再請您將檔案內容貼上來了。
謝謝

**Comment by OowhitecatoO** [comment]
log 如下
環境 Ubuntu 18.04
https://pastebin.com/aMaaxmrH

**Comment by taipower-dreams-tester** [comment]
![2020-12-25_15h27_28](https://user-images.githubusercontent.com/76514336/103125391-f05c1400-46c5-11eb-9c37-a4ac1b51de50.png)
您好，從log中看起來是MySQL拒絕連線，很有可能是沒有正常啟動
請確認MSQL的docker是否有正常在跑，以及是否有錯誤訊息喔

**Comment by HWCHIOU** [comment]
請問 "測試現場資料蒐集器(可控)" 連接Modbus 是哪一種 Gateway ? 一般的 IPC 還是 dnp3 轉 Modbus 的gateway?
