### ISSUE TITLE
無法開始測試

### ISSUE THREAD

**Issue by red81227** [taipower-dreams-tester/dreams-cloud-joint-tester#56]
你好! 我按照流程安裝完之後點擊開始測試就沒反應

![2022-12-22_17-24](https://user-images.githubusercontent.com/46732234/209102224-c4c8d67b-2abb-48a7-8cb2-7e51ad77ccee.png)

查看dreams-cloud-joint-tester_mq-dreams_1的docker log有報錯

![2022-12-22_17-15](https://user-images.githubusercontent.com/46732234/209100616-378709da-61ce-48ea-811b-731bbff9f356.png)

但看ip似乎沒問題
![2022-12-22_17-16](https://user-images.githubusercontent.com/46732234/209100703-3b3acdef-9325-43c5-8555-e0f9df021d0a.png)

可否協助了解一下 萬分感謝!

其他container log
dreams-cloud-joint-tester_mysql_1
![2022-12-22_17-21](https://user-images.githubusercontent.com/46732234/209101808-051b46dd-f82c-4fa0-a345-df155a193383.png)

dreams-cloud-joint-tester_dnp3-master_1

![2022-12-22_17-19](https://user-images.githubusercontent.com/46732234/209101977-a031b1e5-4c99-4717-964c-33f2a55928af.png)

**Comment by taipower-dreams-tester** [comment]
您好，

從網頁console錯誤訊息"send plant Data err"看起來應該是嘗試建立重複的資料，建議您確認一下DB裡面Plant是否已經有資料。如果有建議您將Gateway跟Plant這兩個table裡的資料都清空再試一次看看。

**Comment by red81227** [comment]
刪除後還是卡在同樣的問題。

資料庫裡面的資料長這樣，是正確的嗎？
![2022-12-22_23-02](https://user-images.githubusercontent.com/46732234/209163099-f1bd422a-4c67-40c1-a5b0-a3c584995600.png)

**Comment by red81227** [comment]
將原本的ubtuntu 22退版到18即可進入測試畫面，感謝!
