### ISSUE TITLE
如何通過3系列測試

### ISSUE THREAD

**Issue by coolwang2** [taipower-dreams-tester/dreams-cloud-joint-tester#6]
您好：
請問3系統的測試中，
將逆變器的 PF 已經設定成 90，DREAM 也收到 90，但還在「持續取得資料中…」
這樣算通過嗎？

1. 它還需要取得 bit1to50 開關值的變化才能通過呢？
2. 還是電表的 PF 的值變成 90? 
3. 還是要人工判斷通過？

順便一問，哪些測試是自動通過，哪些是人工判斷通過。
謝謝~~

![image](https://user-images.githubusercontent.com/16569335/103071253-3352b480-45fe-11eb-8632-33d06940bbb9.png)

**Comment by coolwang2** [comment]
這樣算通過嗎？「收到變流器成功回報」

![image](https://user-images.githubusercontent.com/16569335/103072910-84b07300-4601-11eb-81a1-d9cbf7ec3c60.png)

**Comment by taipower-dreams-tester** [comment]
您好，P/PF相關的測試皆為人工判斷。這幾項測試( 3-2 ~ 3-5)主要目的為驗證調控是否成功且有實質效果，因此僅是變流器設定值改變是不夠的(因為也有可能受測廠商的程式謊報)，實際測試時會請工研院幫忙檢證所測到的功率或是功率因數是否符合設定值的範圍。

另外哪些是自動通過應該在網頁介面上都標示的十分清楚，即使是自動通過，實際上還是會人眼檢查數值是否有誤喔。
