### ISSUE TITLE
開發套件詢問

### ISSUE THREAD

**Issue by Roach0857** [taipower-dreams-tester/dreams-cloud-joint-tester#61]
想詢問目前若要開發DNP3 Outstation主流會是用什麼做開發?
我目前是使用C#的[Dnp3](https://github.com/stepfunc/dnp3)做開發
但這個套件比較新，有些功能還沒有開發完，像是多個Outstation對應一個IP的Mster
想雲問各位都是用什麼做開發?

**Comment by taipower-dreams-tester** [comment]
您好，

我們是用 C++ 的 [opendnp3](https://dnp3.github.io/) 開發，您可以參考看看。

**Comment by Roach0857** [comment]
謝謝，已解決
