### ISSUE TITLE
2-4測試問題

### ISSUE THREAD

**Issue by Roach0857** [taipower-dreams-tester/dreams-cloud-joint-tester#62]
關於2-4測試問題
![image](https://github.com/taipower-dreams-tester/dreams-cloud-joint-tester/assets/51991676/71d72351-66e5-4905-b435-1e25ffae4250)
在此頁面按下測試後，有使用Outstation傳送資料後，沒有在此頁面顯示
但在DB中的LogRegistersMeter有新增資料
![image](https://github.com/taipower-dreams-tester/dreams-cloud-joint-tester/assets/51991676/302540a5-ad53-4d35-bb35-32706d896877)
請問為什麼?

**Comment by taipower-dreams-tester** [comment]
您好，

兩個測試案場都要有回傳定時資料喔，從您的 DB 中只看到其中一個。

**Comment by Roach0857** [comment]
99-99-9999-99-9與88-88-8888-88-8都須回傳，已解決，謝謝
