### ISSUE TITLE
部署時發生問題

### ISSUE THREAD

**Issue by superfcu** [taipower-dreams-tester/dreams-cloud-joint-tester#64]
您好, 之前下載部署過一次是正常, 但最近重新下載專案部署時發生問題, 不知道是否哪邊有變更，請幫忙檢視提供意見，感謝。
![螢幕擷取畫面 2024-06-24 095834](https://github.com/taipower-dreams-tester/dreams-cloud-joint-tester/assets/38412486/ca47fe16-963a-4178-84dc-75332f02038e)

**Comment by taipower-dreams-tester** [comment]
Hi @superfcu 

看了一下以後發現應該是我們使用到的前端套件所依賴的套件沒有固定版本，造成新版要求的 nodejs 超過我們所使用的版本

建議可以試著先在 `tester-web/package.json` 裡面，加上以下的設定應該就可以 build 成功了

```json
  "resolutions": {
    "@testing-library/dom": "6.15.0"
  },
```

**Comment by superfcu** [comment]
感謝您的協助，已順利部署。
