### ISSUE TITLE
關於4-1測項資料排序

### ISSUE THREAD

**Issue by derting** [taipower-dreams-tester/dreams-cloud-joint-tester#7]
關於4-1測項，離線上報(定時上報每15分中間隔) 資料的展示邏輯
是否應使用資料收集時間 itemTimestamp，而非伺服器收到時間 atTimestamp 

EX: Outstation間隔10秒依序送出資料A(Time_N), B(Time_N+10), C(Time_N+20)
但Master伺服器收到時間 atTimestamp 卻依序為B(Time_N), A(Time_N+10), C(Time_N+20)

Master伺服器收到時間 atTimestamp 並非完全可以控制順序，此部分沒有邏輯性可依循，
建議應使用Outstation資料收集時間 itemTimestamp 為判斷依據

![image](https://user-images.githubusercontent.com/5178511/103078643-49b43c80-460d-11eb-818c-6171714adb01.png)

**Comment by taipower-dreams-tester** [comment]
您好，這邊我們會再評估，不過基本上斷線31分鐘理應只傳回2筆定時資料，因此順序如何應該不影響測試結果喔。
