### ISSUE TITLE
定時回報定義？

### ISSUE THREAD

**Issue by coolwang2** [taipower-dreams-tester/dreams-cloud-joint-tester#8]
您好：
想請教以下問題
定時回報 Event: Unsolicited Response (Class 1)
一、class 1 的定義是什麼？
    圖上說是 Unsolicited Responses(Class 0)？
    a. 是表示 class1230 都要回傳嗎？ outstation 如何自主發 all class data？
       (目前發現是從 dream 下指令來要 all class data ，outstation 才會回傳)
    b. class1 event 是要發整點的一筆資料，還是從上個整點到這次整點累積沒有超過 deadband 的資料呢？

二、續 a. 問題
    如果 outstation 無法自主發 all class data，那要如何回送 event，才能讓 dream 下指令來要 all class data？
    2-4 / 4-1 / 6-2 的測試是不是都需要 all class data 才能通過呢？

2-4 於整點、15 分、30 分及 45 分主動傳送完整資料。
4-1 模擬 DREAMS 平台離線 31 分鐘後恢復連線，離線期間雲端資料系統須將定時資料暫存系統。恢復連線時模擬 DREAMS 平台將主動發起連線雲端資料系統。
6-2 將現場資料蒐集器復歸，模擬 DREAMS 平台須可收到該案場最近一筆定時資料。
![image](https://user-images.githubusercontent.com/16569335/104153080-5c57af80-541c-11eb-8212-710dcc0aae99.png)

**Comment by taipower-dreams-tester** [comment]
您好，請見以下回答:
問題一
1. 這部分是指將定時(整點)資料以 Class 1 的event 方式回傳
2. 請回傳整點的一筆資料
問題二
請見問題一的1.

相關規範說明，可參考台電公告
https://www.taipower.com.tw/tc/page.aspx?mid=123
