### ISSUE TITLE
關於4-1測試

### ISSUE THREAD

**Issue by akito1010** [taipower-dreams-tester/dreams-cloud-joint-tester#9]
您好~
關於測試4-1 Dreams離線31分再開機要回傳二筆資料部份
我們透過封包測錄程式發現我們傳回去的封包時間是對的
但是它第一台的第二筆時間卻顯示是開機當下的時間(可能是Dreams polling)
依規範回傳整點,15分,30分,45分的Event Data Unsolicited Response(class1)要將object 32 variation 3的flag bit 7改為1做為區分 
覺得是測試程式沒有判斷這個欄位, 而取到別的資料, 導致顯示到別筆資料

感謝

**Comment by taipower-dreams-tester** [comment]
您好，
測試程式本身應該已經把polling關掉，請問方便提供封包側錄檔讓我們確認一下嗎?

**Comment by akito1010** [comment]
您好，再請教一個問題

測試程式4-1，5-2是否只顯示Flag 第7個bit為1的數據

謝謝

**Comment by akito1010** [comment]
4-1 測試時，Dreams重啟後有polling
1611187947390 - <-LL- - server - Function: PRI_UNCONFIRMED_USER_DATA Dest: 4 Source: 3 Length: 17
1611187947390 - <-LL- - server - 05 64 11 C4 04 00 03 00 4E EF
1611187947390 - <-LL- - server - C0 C0 15 3C 02 06 3C 03 06 3C 04 06 1A 55
1611187947390 - <-TL- - OT-4 - FIR: 1 FIN: 1 SEQ: 0 LEN: 11
1611187947390 - <-AL- - OT-4 - C0 15 3C 02 06 3C 03 06 3C 04 06
1611187947390 - <-AL- - OT-4 - FIR: 1 FIN: 1 CON: 0 UNS: 0 SEQ: 0 FUNC: DISABLE_UNSOLICITED
1611187947391 - <-AL- - OT-4 - 060,002 - Class Data - Class 1 - all objects
1611187947391 - <-AL- - OT-4 - 060,003 - Class Data - Class 2 - all objects
1611187947391 - <-AL- - OT-4 - 060,004 - Class Data - Class 3 - all objects

**Comment by taipower-dreams-tester** [comment]
您好，
關於Flag第7個bit的部分，目前此規範正在研擬修正，將由台電對外公布。

另外更正一下之前的回覆，polling的部分目前僅有在DREAMS重啟之後會trigger一次。這次polling為規範之中要求，請參考["台灣電力公司配電級再生能源監控設備(再生能源監控設備/業者雲端資料系統)與 DREAMS傳輸需求技術規範摘要"](https://www.taipower.com.tw/upload/123/2021011514372039094.pdf) 的「二、訊息及資料處理」裡面第二條。

因應這項要求，擬將測試程式4-1改為顯示斷線後最早收到的三筆資料(原為兩筆)。第一筆為輪詢，後兩筆應為斷線回補之定時資料。待修改完成後將於此通知。

**Comment by akito1010** [comment]
您好，
5-2 跟 6-2 在測試程式部分，是否也會發送polling，
如果是的話，5-2跟6-2測試程式在顯示部分是否應該過濾掉polling的數據

以下是5-2 測試時
![1611284829292](https://user-images.githubusercontent.com/77622843/105440864-4fe81800-5ca2-11eb-93e3-33f8e9c39b64.jpg)

**Comment by taipower-dreams-tester** [comment]
您好，
理論上不應該發送polling，這部分我們會盡快查明原因後回覆

**Comment by dnptester** [comment]
您好，再請教有關4-1當收到All Class時，最後要傳送的Class 0的時間是定時回傳的時間，還是當下要傳送時的時間

**Comment by taipower-dreams-tester** [comment]
您好，
應該是當下要傳送的時間喔

**Comment by coolwang2** [comment]
您好：
簡易描述一下 4-1 流程：
當 4-1 按測試後，dream 斷線 31 min 會經過兩個整點(class1)，而且該兩筆整點資料因斷線而 案場無法送出給 dream
當 dream 復線時, 會下 all class request, 而回傳順序是 class 1/2/3/0
所以 4-1 的頁面會顯示資料如下：
 ->整點1 (class1)
 ->整點2 (class1)
 ->class2 (無)
 ->class3 (無定義)
 ->靜態(class0)
依這樣的更新順序，class0 的時間戳應該就是「整點2資料」最後更新的狀態
所以靜態(class0)當下的資料狀態會與「整點2資料」相同。
下圖是目前測到的情況，想說是不是 AI table 的時間戳參數那邊設定有問題呢？還是我們對 dnp 有誤解？
有點困難讓靜態(class0)資料的時間戳變成復線當下的時間。
是當 dream 復線時，利用 class2 來更新時間戳參數嗎？

延伸問題：時間戳平實有要用 class2 回報回去嗎？
謝謝

![image](https://user-images.githubusercontent.com/16569335/105824120-ec8b1c80-5ff8-11eb-97df-bffc543489c8.png)

**Comment by taipower-dreams-tester** [comment]
您好，
針對class 0應該要回的是收到request當下所有點位的最新狀態(包含因deadband而更新的數值)，而非最後一筆整點資料，因此時間戳的點位應該也要更新成最後一筆定時或deadband資料的時間戳喔。

另外class 2的event回傳本身就會帶時間戳(非點位)，並且時間戳點位不需要做deadband回傳，因此平時class 2的回傳不用額外再把時間戳點位傳回來，但DNP3本身event帶的時間戳要給對喔。

如果還有疑問再請提出，謝謝

**Comment by coolwang2** [comment]
您好：
DNP3本身event帶的時間戳要給對，請問怎樣的時間戳單位是正確的呢？
因為是用 opendnp3 裡面的函式來取得時間，所以不確定 dream 是收什麼才正確。
(想說 dream 底層的 master 應也是 opendnp3)

謝謝

**Comment by taipower-dreams-tester** [comment]
您好，
一、
如果沒有任何deadband更新的話的確如此，不過建議在deadband一直發生的情況下測試以確保程式行為正確。以工研院的測試環境是可以做到的。

二、
如果是opendnp3的話就只有您跑outstation程式的機器有沒有確實做到網路校時的問題而已。如果有做到這點就不必擔心囉。

三、
目前測試程式裡顯示的「收到資料時間」是DNP3 master收到資料當下的系統時間。
而「時間戳」比較複雜一點點，基本上是時間戳點位的值，但deadband的情況下目前會是收到資料當下的系統時間。
(因為deadband不會有點位時間戳，但應該要採用非點位時間戳)。
不過這點目前並不影響測試結果，因此我們後續才會排入修正。

四、
class 0是static而非event，因此正常實作上應該要是完全不影響的

**Comment by coolwang2** [comment]
您好：
感謝您即時的回覆，
不過，還是覺得哪裡有衝突：

您說：
1. class 0  時間戳的點位應該更新成 deadband 資料的時間戳
   解讀：deadband event 所附帶的時間「會影響」 class 0  的時間戳點位。
2. class 0 正常實作上應該要是完全不影響 event 附帶的時間戳
   解讀：event 附帶的時間戳「不會影響」 class 0  的時間戳點位。
3. 時間戳點位不需要做 deadband 回傳
   解讀：時間戳點位不需要做 deadband event 回傳

總結：
要以怎樣的方式讓 「class 0  時間戳的點位」(i.e. 上圖的「時間戳」) 去顯示成 dream 復線當下的時間點呢？

謝謝

**Comment by taipower-dreams-tester** [comment]
您好，
「class 0 時間戳的點位應該更新成 deadband 資料的時間戳」這只是讓class 0的時間戳點位顯示dreams復線當下時間點的方式之一。您可以想成有一個所有點位最新數值的暫存區，每次outstation收到新的數值(定時 or deadband)都更新它，而當收到master的polling時便將這個暫存區的數據回傳。

當然這只是其中一種做法，主要目的是保證master的polling會拿到當下最新的數值(當然也包含時間戳)。

**Comment by dnptester** [comment]
樓上coolwang2 這位同學我們也一樣遇到這些問題，我想問一下taipower-dreams-tester 管理員，您是在輔導大家可以過關，還是希望我們不要過關，就把您要的資料直接告訴大家不就好了

**Comment by dnptester** [comment]
我還以為只有我們測試有問題，原來同業的測試也碰到的狀況都一樣:

Q1 下面是台電端提供的Class 0說明，並沒有詳細說明時間戳的格式?
Q2  deadband event 所附帶的時間「會影響」時間戳, 我們上上週去測時現場也不會有Deadband的產生，為何Class0時間戳
       與時間有關?

1. Static Data Solicited Response (Class0)
(1)當 DREAMS 重新啟動或通訊中斷一段時間後(時間為參數，可調整)將執行全體資料輪詢，當 DREAMS 發出輪詢指令後，若
  Outstation 無回應，DREAMS 須重新輪詢並要求 Outstation 將資料依 Class 1、 Class 2、 Class0 等級的順序傳送。

(2)若輪詢結果有 Event 時，DREAMS 須以 Application Layer Confirm回應。

(3)Outstation 資料以 Data Link Layer 規定之資料長度 (應用層 249Bytes) 分批傳送回DREAMS，DREAMS於收到最後一批資料後，
以 Application Layer 回應收到資料；另中間批次 Data Link Layer傳送資料由兩端之底層 TCP 協定負責執行資料收送、確認及重送
工作，Data Link Layer 無須回應資料收到

(4)Static 資料以 Class 0 傳送，而 Event 資料則分別以 Class 1、Class2 方式依序傳送。

**Comment by taipower-dreams-tester** [comment]
您好，
Q1: 目前規範中class 0的用途僅用於讓台電端能夠手動取得當前最新的資料，因此時間戳也理當帶上取得最新資料的時間點。規範中未說明清楚的部分我們會再請台電協助將更新版放上去。
Q2: 不好意思這方面解說可能不夠清楚造成誤解。Class 0所帶的時間戳與deadband時間並沒有直接關係，僅只是若每秒都有deadband產生，它理應跟最後一筆deadband非常接近或相等而已。

**Comment by coolwang2** [comment]
您好：
對於4-1測試不明白的人問說：
「經與台電確認4-1的polling 資料的時間戳是位址32的雲端系統時間，為何畫面顯示成定時的時間戳？」
再麻煩您撥空回答
謝謝

**Comment by taipower-dreams-tester** [comment]
您好，
單純就這樣的描述我們比較難確定問題是什麼喔。
基本上4-1目前會顯示斷線後收到的頭三筆資料，而顯示的時間戳，只要有傳位址32都會是以它為主，因此理論上應該不會有所描述的情形發生。建議提供詳細的截圖以及傳輸封包協助我們釐清一下實際的狀況喔。
謝謝!

**Comment by topcminwer** [comment]
您好：

想確認一件事情是：
假設我有一個所有點位數值的暫存區，
而這個暫存區會經由class1 event和class2 event來更新，
我們可以認定暫存區的數值為當下最新的資料，是這個意思嗎？

謝謝！

**Comment by taipower-dreams-tester** [comment]
您好，
這只是一種實作方式，並不一定保證數值會是最新喔。
基本上還是要看class 1 event(定時)和class 2 event(deadband)是否有在該回傳的時候回傳。
在上面的前提下，才比較能認定暫存區的數值是相對最新的。
(亦即所有點位數值跟實際的當前值之差距，都沒有超過deadband的%數)
(當然如果在收到DNP3 polling時能直接跟案場裝置讀取當前資料，會是更精確的作法)

**Comment by sunwareIzumi** [comment]
不好意思 我想請問一下
4-1這項
要回應三筆資料

是 回應 
class 1 * 2 + class 2 * 1 ?
or
class 1 * 3 ?

哪個才是 正確的 目前知道 回應 class 1 * 2 + class 0 * 1 測試不會通過
class 0 的資料 不會進到 LogRegistersMeter 表中

**Comment by taipower-dreams-tester** [comment]
同樣問題在[#31](https://github.com/taipower-dreams-tester/dreams-cloud-joint-tester/issues/31)已經回答過，故close此Issue
